=== guyue123/ly/ly-luoying-desktop/assets/Scenes/LuoYing/data/meta/position.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://luoying.huliqing.name"
           xmlns="http://luoying.huliqing.name"
           elementFormDefault="qualified" >
    
    <xs:include schemaLocation="./base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="positionRandomSphere" />
                <xs:element ref="positionRandomBox" />
                <xs:element ref="positionRandomCircle" />
                <xs:element ref="positionFixedPoint" />
                <xs:element ref="positionView" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="positionView">
        <xs:annotation>
            <xs:documentation>视图界面上的位置点</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="positionBase">
                    <xs:attribute name="corner" use="required" >
                        <xs:annotation>
                            <xs:documentation>角落位置，支持: LB,LC,LT,CB,CC,CT,RB,RC,RT</xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="LB" />
                                <xs:enumeration value="LC" />
                                <xs:enumeration value="LT" />
                                <xs:enumeration value="CB" />
                                <xs:enumeration value="CC" />
                                <xs:enumeration value="CT" />
                                <xs:enumeration value="RB" />
                                <xs:enumeration value="RC" />
                                <xs:enumeration value="RT" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="marginWeight" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                marginWeight, 格式："left,top,right,bottom", 如: "0.1,0.1,0,0" 
                                表示距离左边"0.1 * ScreenWidth"和上边"0.1 * ScreenHeight"像素的位置.
                                注意:这里表示的是屏幕宽高度的权重，各个分值取值范围: 0.0~`1.0
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="positionFixedPoint">
        <xs:annotation>
            <xs:documentation>点shape</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="positionBase">
                    <xs:attribute name="point" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>e.g. "0,0,0"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="positionRandomCircle">
        <xs:annotation>
            <xs:documentation>圆形shape,通过设置不同参数可以形成:圆环\圆面\圆筒\圆柱等形式的shape</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="positionBase">
                    <xs:attribute name="plane" use="required">
                        <xs:annotation>
                            <xs:documentation>shape所在的原始面</xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="xy" />
                                <xs:enumeration value="xz" />
                                <xs:enumeration value="yz" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="minRadius" type="xs:decimal" use="required">
                        <xs:annotation>
                            <xs:documentation>shape的内半径</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="maxRadius" type="xs:decimal" use="required">
                        <xs:annotation>
                            <xs:documentation>shape的外半径,如果设置和minRadius一致,则可以形成一个圆环</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="minOffset" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>产生的粒子位置的偏移最小值,格式："x,y,z"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="maxOffset" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>产生的粒子位置的偏移最大值,通过设置
                                和minOffset不同的值可形成圆筒或圆柱,格式："x,y,z".
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="order" type="bool" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                是否按顺序产生粒子位置，按顺序是指绕着圆周顺序产生粒子,
                                默认情况下粒子位置是在模型内随机产生的,只有order设为true时才按顺序。
                                圆周的半径由minRadius和maxRadius控制。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="orderInvert" type="bool" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                当order=true时，默认为逆时针顺序产生粒子位置，使用orderInvert来反转顺序
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="orderSize" type="xs:integer" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                当order=true时，粒子按圆周顺序产生，orderSize指定了在圆周上多少个位置作为
    一个圆周周期，比如orderSize=6,则在圆周上产生6个粒子位置之后，系统会重新
    计算一个随机圆周半径（由minRadius和maxRadius决定），然后重新按顺序产生6个粒子
    位置,这些粒子位置是在圆周上平均分布的，如orderSize=6,则在圆周上的每60度会
    产生一个粒子位置(该值必须大于0)
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="orderStartDegree" type="xs:decimal" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                当order=true时，可指定一个开始角度(默认0),注:是角度,非弧度
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="positionRandomBox">
        <xs:annotation>
            <xs:documentation>Box shape</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="positionBase">
                    <xs:attribute name="min" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>e.g. "-1,-1,-1"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="max" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>e.g. "1,1,1"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="positionRandomSphere">
        <xs:annotation>
            <xs:documentation>Sphere shape</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="positionBase">
                    <xs:attribute name="center" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>e.g. "0,0,0"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="radius" type="xs:decimal" use="required">
                        <xs:annotation>
                            <xs:documentation>e.g. "2.0"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="positionBase">
        <xs:complexContent>
            <xs:extension base="base"> 
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
</xs:schema>

=== guyue123/ly/ly-luoying-desktop/bin/data/object/position.xml
<?xml version="1.0" encoding="UTF-8"?>

<root xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name ../../../../ly-kernel/src/LuoYing/Data/meta/position.xsd'>

    <!--=====================================================================-->
    <!--通用配置-->
    <!--=====================================================================-->

    <positionFixedPoint id="positionOrigin" point="0, 0, 0" />
    
    <positionRandomSphere id="positionCommonSp0_5" center="0,0,0" radius="0.5" />
    <positionRandomSphere id="positionCommonSp0_7" center="0,0,0" radius="0.7" />
    <positionRandomSphere id="positionCommonSp1_0" center="0,0,0" radius="1" />

    <!--默认的射击点1-->
    <positionFixedPoint id="positionDefShotUp" point="0,2,7" />
    <positionFixedPoint id="positionDefShotLeft" point="2,1,7" />
    <positionFixedPoint id="positionDefShotRight" point="-2,1,7" />
    
    <!--=====================================================================-->
    <!--特定配置-->
    <!--=====================================================================-->

    <positionRandomSphere id="positionFlameShape" center="0, 0, 0" radius="1" />
    
    <positionRandomSphere id="positionFlashShape" center="0, 0, 0" radius="0.05" />

    <positionRandomSphere id="positionRandomFire" center="0,0,0" radius="1" />
    
    <!--在一个圆柱的范围内-->
    <positionRandomCircle id="positionCylinder" plane="xz" minRadius="0.5" maxRadius="0.5" minOffset="0,0.8,0" maxOffset="0,0.8,0" />
    
    <positionFixedPoint id="positionSwordSpark" point="0,0,0" />
    
    <!-- 用于召换野兽 -->
    <positionRandomSphere id="positionHalo" center="0, 1, 0" radius="2.5" />
    
    <!-- 用于星光传送中的星光发射 -->
    <positionRandomSphere id="positionHaloExp" center="0, 0.5, 0" radius="1" />
    
    <!-- 用于黑暗祭坛 -->
    <positionRandomCircle id="positionAltar" plane="xz" minRadius="0" maxRadius="2"/>
    <positionRandomSphere id="positionAltarHalo" center="0,0,0" radius="2.5" />
    
    <!-- 闪电箭shape -->
    <positionRandomSphere id="positionLightningShotBolt" center="0, 0, 0" radius="1" />
    <positionRandomSphere id="positionLightningShotHit" center="0, 0, 0" radius="1.5" />
    <positionRandomCircle id="positionLightningShotBullet2" plane="xy" minRadius="0.5" maxRadius="0.5" order="1" orderSize="7" orderInvert="0" />

    <!-- 状态：疾风步,音障和退散粒子 -->
    <positionRandomSphere id="positionStateWindWalkStart" center="0,1,0" radius="2.5" />
    <positionFixedPoint  id="positionStateWindWalk" point="0, 0.75, 0" />
    
    <!--状态：晕眩，金星旋转-->
    <positionRandomCircle id="positionShapeStun" plane="xz" minRadius="0.3" maxRadius="0.3" maxOffset="0,0.1,0" />
    
    <!--落樱飞舞-->
    <positionRandomCircle id="positionDanceSakuraHalo" plane="xy" minRadius="0" maxRadius="2.5" />
    <positionRandomCircle id="positionDanceSakuraJump" plane="xz" minRadius="0.5" maxRadius="0.5" />
    <positionRandomCircle id="positionDanceSakuraWaypoint" des="for skill waypoints" plane="xy" minRadius="2" maxRadius="4" />
    <positionRandomCircle id="positionDanceSakuraWaypoint2" des="for skill waypoints" plane="xy" minRadius="2" maxRadius="4" minOffset="0,0,-3" maxOffset="0,0,-3" />
    
    <!--石塔黑烟-->
    <positionRandomCircle id="positionTowerSmoke" plane="xy" minRadius="0" maxRadius="0" minOffset="0,0,-0.5" maxOffset="0,0,-0.5" />
    
    <!--=====================================================================-->
    <!--电光火石-->
    <!--=====================================================================-->
    <!--手上闪电-->
    <positionRandomSphere id="positionShapeLightning" center="0, 0, 0" radius="0.2" />
    <!--子弹-->
    <positionFixedPoint id="positionFlowLight" point="0,1,5" />

    <!--=====================================================================-->
    <!--BUFF-->
    <!--=====================================================================-->
    <positionFixedPoint id="positionShapeBuff" point="0,2.5,8" />
    
    <!--=====================================================================-->
    <!--复活术-->
    <!--=====================================================================-->    
    <positionRandomCircle id="positionShapeReborn" plane="xz" minRadius="0" maxRadius="2" minOffset="0,0,0" maxOffset="0,2,0" />
    
    <!--=====================================================================-->
    <!--冲击波-->
    <!--=====================================================================-->    
    <positionFixedPoint id="positionShapeWave" point="-2,3,10" />
    
    <!--=====================================================================-->
    <!--黄金宝箱计时面板位置路径点:右上角-->
    <!--=====================================================================-->    
    <positionView id="positionTreasureP1" corner="LB" />
    <positionView id="positionTreasureP2" corner="CB" marginWeight="0,0,0,0.2" />
    <positionView id="positionTreasureP3" corner="RT" marginWeight="0,0,0.3,0" />
    <positionView id="positionTreasureP4" corner="RT" marginWeight="0,0.27,0.15,0" />
    
    <!--=====================================================================-->
    <!--二刀流冲击波-->
    <!--=====================================================================-->    
    <positionRandomCircle id="positionWaveShape" plane="xz" minRadius="2" maxRadius="2" minOffset="0,0,0" maxOffset="0,0.5,0" />
    
    <!--=====================================================================-->
    <!--test-->
    <!--=====================================================================-->    
    <positionRandomCircle id="positionShapePZS" plane="xz" minRadius="0" maxRadius="0.3" minOffset="0,0,0" maxOffset="0,0,0" />
    <positionRandomCircle id="positionShapePZC" plane="xz" minRadius="0" maxRadius="2" minOffset="0,4,0" maxOffset="0,6,0"/>
    <positionRandomCircle id="positionShapePZE" plane="xz" minRadius="0" maxRadius="2" minOffset="0,8,0" maxOffset="0,10,0"/>

    
</root>

=== guyue123/ly/ly-luoying-desktop/assets/Scenes/LuoYing/data/position.xml
<?xml version="1.0" encoding="UTF-8"?>

<root xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name meta/position.xsd'>

    <!--=====================================================================-->
    <!--通用配置-->
    <!--=====================================================================-->

    <positionFixedPoint id="positionOrigin" point="0, 0, 0" />
    
    <positionRandomSphere id="positionCommonSp0_5" center="0,0,0" radius="0.5" />
    <positionRandomSphere id="positionCommonSp0_7" center="0,0,0" radius="0.7" />
    <positionRandomSphere id="positionCommonSp1_0" center="0,0,0" radius="1" />

    <!--默认的射击点-->
    <positionFixedPoint id="positionDefShotUp" point="0,2,7" />
    <positionFixedPoint id="positionDefShotLeft" point="2,1,7" />
    <positionFixedPoint id="positionDefShotRight" point="-2,1,7" />
    
    <!--=====================================================================-->
    <!--特定配置-->
    <!--=====================================================================-->

    <positionRandomSphere id="positionFlameShape" center="0, 0, 0" radius="1" />
    
    <positionRandomSphere id="positionFlashShape" center="0, 0, 0" radius="0.05" />
    
</root>
