=== guyue123/ly/ly-kernel/bin/LuoYingSys/Data/meta/anim.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://luoying.huliqing.name"
           xmlns="http://luoying.huliqing.name"
           elementFormDefault="qualified" >
    
    <xs:include schemaLocation="./animBase.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="animMove" />
                <xs:element ref="animCurveMove" />
                <xs:element ref="animRotation" />
                <xs:element ref="animInterpolateRotation" />
                <xs:element ref="animRandomRotation" />
                <xs:element ref="animScale" />
                <xs:element ref="animColor" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="animColor">
        <xs:annotation>
            <xs:documentation>
                颜色动画
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="animBase">
                    <xs:attribute name="startColor" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>开始颜色,如"0.5,0.5,0.5,1"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="endColor" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>结束颜色,如"1,1,1,1"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="animScale">
        <xs:annotation>
            <xs:documentation>
                缩放动画
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="animBase">
                    <xs:attribute name="startScale" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>开始的缩放值,如"1,1,1"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="endScale" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>结束时的缩放值,如"0.1,0.1,0.1"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="restore" type="bool" use="optional">
                        <xs:annotation>
                            <xs:documentation>是否在动画结束时复原缩放比率</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="scaleOffset" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>缩放点的偏移，格式: "x,y,z", 默认情况下以物体原点为缩放点进行缩放。</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="animRandomRotation">
        <xs:annotation>
            <xs:documentation>
                随机旋转动画
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="animBase">
                    <xs:attribute name="minDegree" type="xs:decimal" use="optional">
                        <xs:annotation>
                            <xs:documentation>最小旋转角度（非弧度）</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="maxDegree" type="xs:decimal" use="optional">
                        <xs:annotation>
                            <xs:documentation>最大旋转角度（非弧度）</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="axis" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>旋转轴，格式: "x,y,z"，如果没有指定这个参数，则使用随机生成的旋转轴</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="animRotation">
        <xs:annotation>
            <xs:documentation>
                旋转动画
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="animBase">
                    <xs:attribute name="axis" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>旋转轴,如"0,1,0"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="degree" type="xs:decimal" use="required">
                        <xs:annotation>
                            <xs:documentation>旋转角度，不是弧度</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="invert" type="bool" use="required">
                        <xs:annotation>
                            <xs:documentation>是否反方向旋转</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="restore" type="bool" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                旋转结束时是否复原开始时的旋转属性,如果打开这个参数，则动画开始时会记住
                                物体的旋转前的旋转属性，在结束的时候再复原该旋转属性。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="animInterpolateRotation">
        <xs:annotation>
            <xs:documentation>插值旋转动画</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="animBase">
                    <xs:attribute name="start" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定开始旋转值，格式： "x,y,z"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="end" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定结束旋转值， 格式："x,y,z"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="animCurveMove">
        <xs:annotation>
            <xs:documentation>
                曲线移动动画
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="animBase">
                    <xs:attribute name="waypoints" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                路径点,格式："position1,position2,..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="curveTension" type="xs:decimal" use="optional" />
                    <xs:attribute name="facePath" type="bool" use="optional" />
                    <xs:attribute name="rotationOffset" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>初始旋转, 格式："x,y,z",分别表示在指定轴上的旋转度数</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="animMove">
        <xs:annotation>
            <xs:documentation>
                移动动画
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="animBase">
                    <xs:attribute name="startPos" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>开始位置,如"0,0,0"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="startPosOffset" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>开始位置的偏移,如"0,0,0"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="endPos" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>结束位置,如"1,1,1"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="endPosOffset" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>结束位置的偏移,如"1,1,1"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="facing" type="bool" use="optional">
                        <xs:annotation>
                            <xs:documentation>是否朝向目标</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== guyue123/ly/ly-luoying-desktop/bin/LuoYing/data/anim.xml
<?xml version="1.0" encoding="UTF-8"?>

<root 
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name meta/anim.xsd' >
    
    <!--==========================================================================-->
    <!-- 通用Animation -->
    <!-- "X,Y,Z"代表轴向; i代表invert; S代表show; H代表hide; I代表fadeIn; O代表fadeOut-->
    <!--==========================================================================-->
    <animRotation id="animCommonRotX" loop="loop" axis="1,0,0" degree="360" invert="0" />
    <animRotation id="animCommonRotY" loop="loop" axis="0,1,0" degree="360" invert="0" />
    <animRotation id="animCommonRotZ" loop="loop" axis="0,0,1" degree="360" invert="0" />
    <animRotation id="animCommonRotZi" loop="loop" axis="0,0,1" degree="360" invert="1" />
    <animRandomRotation id="animCommonRotRandom" minDegree="0" maxDegree="360" />
    
    <animScale id="animCommonScaleS" startScale="0.01,0.01,0.01" endScale="1,1,1" motionType="Bezier" bezierFactor="0,0,1.5,1" />
    <animScale id="animCommonScaleH" startScale="1,1,1" endScale="0.01,0.01,0.01" />
    
    <animColor id="animCommonColorI" startColor="0,0,0,0" endColor="1,1,1,1" />
    <animColor id="animCommonColorI2" startColor="0,0,0,0" endColor="2,2,2,2" />
    <animColor id="animCommonColorI3" useTime="0.3" startColor="0,0,0,0" endColor="3,3,3,3" />
    <animColor id="animCommonColorO" startColor="1,1,1,1" endColor="0,0,0,0" />
    <animColor id="animCommonColorO2" startColor="2,2,2,2" endColor="0,0,0,0" />
    <animColor id="animCommonColorO3" startColor="3,3,3,3" endColor="0,0,0,0" />
    
    <!--==========================================================================-->
    <!--刀光剑影特效动画-->
    <!--==========================================================================-->
    <animColor id="animSwordShadowColor" useTime="0.4" startColor="2,2,2,2" endColor="0,0,0,0" />
    
    <animMove id="animSwordShadow1Move"  useTime="0.4" startPos="0,0,0" endPos="0,5,0" facing="0" />
    <animRotation id="animSwordShadow1Rot" useTime="0.4" axis="0,1,0" degree="30" invert="0" restore="1" />

    <animRotation id="animSwordShadow2Rot" useTime="0.4" axis="0,1,0" degree="180" invert="1" restore="1" />
    <animMove id="animSwordShadow2Move" useTime="0.4" startPos="0,0,0" endPos="0,0,3" facing="0" />

    <animRotation id="animSwordShadow3Rot" useTime="0.4" axis="0,1,0" degree="180" invert="0" restore="1" />
    <animMove id="animSwordShadow3Move" useTime="0.4" startPos="0,0,0" endPos="0,0,3" facing="0" />
    
    <!--==========================================================================-->
    <!--默认的UI动画-->
    <!--==========================================================================-->
    <animMove id="animViewMove" useTime="0.3" startPosOffset="0,-70,0" endPosOffset="0,0,0" motionType="Bezier" bezierFactor="0,0,1.5,1"
              facing="0" />
    
    <!--==========================================================================-->
    <!--野兽召唤-->
    <!--==========================================================================-->
    <animRotation id="animMagicCircleRotY" useTime="4" loop="loop" axis="0,1,0" degree="360" invert="0" />
    <animScale id="animMagicCircleScaleS" useTime="0.5"  startScale="0.01,0.01,0.01" endScale="1,1,1" motionType="Bezier" bezierFactor="0,0,1.5,1" />
    <animScale id="animMagicCircleScaleH" useTime="0.3" startScale="0.9,0.9,0.9" endScale="0.01,0.01,0.01" />
    <animColor id="animMagicCircleColor" useTime="0.5" loop="cycle"  startColor="3,3,3,1" endColor="0.3,0.3,0.3,0.3" />
    <animRotation id="animMagicCircleHaloRotY" useTime="4" loop="loop" axis="0,1,0" degree="360" invert="1" />
    <animScale id="animMagicCircleHaloScaleS" useTime="0.5"  startScale="0.01,0.01,0.01" endScale="1,1,1" motionType="Bezier" bezierFactor="0,0,1.5,1" />
    <animScale id="animMagicCircleHaloScaleH" useTime="0.3" startScale="1,1,1" endScale="0.01,0.01,0.01" />
    
    <!--==========================================================================-->
    <!--星光传送-->
    <!--==========================================================================-->
    <animScale id="animBackTownHaloScaleS" extends="animCommonScaleS" useTime="0.5" />
    <animScale id="animBackTownHaloScaleH" extends="animCommonScaleH" useTime="0.15" />
    <animScale id="animBackTownScaleS" extends="animCommonScaleS" useTime="0.5" />
    <animRotation id="animBackTownCircle" useTime="1.8" loop="loop" axis="0,1,0" degree="360" invert="0" />
    <animColor id="animBackTownColor" useTime="0.33" loop="cycle" startColor="3,3,3,1" endColor="0.75,0.75,0.75,0.75" />
    
    <!--==========================================================================-->
    <!--晕眩：金星旋转-->
    <!--==========================================================================-->
    <animRotation id="animStateStunRot" useTime="6" loop="loop" axis="0,1,0" degree="360" invert="0" />
    
    <!--==========================================================================-->
    <!--闪电箭:闪光的出现-->
    <!--==========================================================================-->
    <animRotation id="animLightningShotRot" useTime="1" loop="loop" axis="0,0,1" degree="360" invert="1" />
    <animScale id="animLightningShotRotScale" useTime="1" startScale="1,1,1" endScale="0.01,0.01,0.01" />
    <animScale id="animLightningShotFlareScaleShow" useTime="0.3" startScale="10,10,10"  endScale="0.02,0.02,0.02" />
    <animRotation id="animLightningShotRot" useTime="0.64" loop="loop" axis="0,0,1" degree="360" invert="1" />
    
    <!--==========================================================================-->
    <!--疾风步-->
    <!--==========================================================================-->
    <animRotation id="animStateWindWalkStartRot" useTime="1" loop="loop" axis="0,1,0" degree="360" invert="0" />
    <animScale id="animStateWindWalkStartScale" useTime="1" startScale="1,1,1" endScale="0.1,0.1,0.1" />
    
    <!--==========================================================================-->
    <!--落樱飞舞-->
    <!--==========================================================================-->
    <animRotation id="animDanceSakuraRot" useTime="2.3" loop="loop" axis="0,0,1" degree="720" invert="0" />
    <animColor id="animDanceSakuraColor" useTime="0.3" startColor="0,0,0,0"    endColor="3,3,3,3" />
    <animScale id="animDanceSakuraScaleHide" useTime="0.3" startScale="10,10,10" endScale="0.02,0.02,1" />
    <animScale id="animDanceSakuraMagicStartScale" useTime="0.3" startScale="0.1,0.1,0.1" endScale="1.2,1.2,1.2" motionType="Bezier" bezierFactor="0,0,1.5,1" />
    <animScale id="animDanceSakuraMagicEndScale" useTime="0.3" loop="dontLoop" startScale="1.2,1.2,1.2" endScale="0.1,0.1,0.1" />
    <animColor id="animDanceSakuraMagicStartColor" useTime="0.3" loop="dontLoop" startColor="0.5,0.5,0.5,0.5" endColor="3,3,3,1" />
    <animColor id="animDanceSakuraMagicDisplayColor" useTime="0.33" loop="cycle" startColor="3,3,3,1" endColor="0.75,0.75,0.75,0.75" />
    <animScale id="animDanceSakuraDirtShow" useTime="0.5"  startScale="0.01,0.01,0.01" endScale="4,2,4" />

    <!--==========================================================================-->
    <!--冲击波-->
    <!--==========================================================================-->
    <!--子弹的旋转-->
    <animRotation id="animWave" useTime="1.66" loop="loop" axis="0,0,1" degree="360" invert="0" />
    <!--卷起的烟雾-->
    <animRotation id="animWaveSmokeRot" useTime="2" loop="loop" axis="0,1,0" degree="360" invert="0" />
    <animScale id="animWaveSmokeScale"  useTime="3" startScale="0.2,0.2,0.2" endScale="2,2,2" />
    
    <!--==========================================================================-->
    <!--黄金宝箱：倒计时面板出现时的动画-->
    <!--==========================================================================-->
    <animCurveMove id="animTreasureTimer" useTime="0.75" useSine="1" waypoints="positionTreasureP1,positionTreasureP2,positionTreasureP3,positionTreasureP4" />

    <!--==========================================================================-->
    <!--冰冻特效：effectFrozenIce冰柱的随机旋转,使用时间非常小，所以不会看到旋转动画
    只是为获得一个随机旋转角度。让每次释放冰柱的时候都使用随机旋转-->
    <!--==========================================================================-->
    <animScale id="animFrozenIceScale" extends="animCommonScaleS" useTime="0.3" />
    <animRandomRotation id="animFrozenIceRot" useTime="0.3" minDegree="180" maxDegree="360" axis="0,1,0" />
    
    <!--==========================================================================-->
    <!--复活术-->
    <!--==========================================================================-->
    <animScale id="animRebornScaleS" extends="animCommonScaleS" useTime="0.5" />
    <animRotation id="animRebornRot" extends="animCommonRotY" useTime="0.5" />
    <animScale id="animRebornScaleH" extends="animCommonScaleH" useTime="0.3" />
    
    <!--==========================================================================-->
    <!--学习技能: effectLearnSkill-->
    <!--==========================================================================-->
    <animRotation id="animLearnSkillRotY" useTime="4" loop="loop" axis="0,1,0" degree="360" invert="0" />
    
    <!--冰霜减速状态的动画-->
    <animColor id="animColorFrost" useTime="0.5" startColor="0.5,0.5,1,1" endColor="0.75,0.75,1,1" loop="cycle" />
</root>
