=== guyue123/ly/ly-kernel/bin/LuoYingSys/Data/meta/attribute.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://luoying.huliqing.name"
           xmlns="http://luoying.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="./base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="attributeBoolean" />
                <xs:element ref="attributeColor" />
                <xs:element ref="attributeFloat" />
                <xs:element ref="attributeGroup" />
                <xs:element ref="attributeInteger" />
                <xs:element ref="attributeLevelFloat" />
                <xs:element ref="attributeLevelInteger" />
                <xs:element ref="attributeLimitInteger" />
                <xs:element ref="attributeLong" />
                <xs:element ref="attributeRelateBoolean" />
                <xs:element ref="attributeString" />
                <xs:element ref="attributeStringList" />
                <xs:element ref="attributeVector2f" />
                <xs:element ref="attributeVector3f" />
                <xs:element ref="attributeVector4f" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeBoolean" >
        <xs:annotation>
            <xs:documentation>整数类型的属性</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="bool" >
                        <xs:annotation><xs:documentation>属性初始值</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeColor" >
        <xs:annotation>
            <xs:documentation>整数类型的属性</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:string" >
                        <xs:annotation><xs:documentation>颜色属性值，格式："r,g,b,a", 示例："1.0, 1.0, 1.0, 1.0"</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeFloat" >
        <xs:annotation>
            <xs:documentation>整数类型的属性</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:decimals" use="optional" >
                        <xs:annotation><xs:documentation>属性初始值, 可以是float或int值.</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeGroup" >
        <xs:annotation>
            <xs:documentation>
                属性组
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="attributes" type="xs:string" use="required" >
                        <xs:annotation><xs:documentation>添加其它属性ID, 格式："attributeId1,attributeId2,..."</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeInteger" >
        <xs:annotation>
            <xs:documentation>整数类型的属性</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:integer" use="optional" >
                        <xs:annotation><xs:documentation>属性初始值，必须是int值.</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeLevelFloat" >
        <xs:annotation>
            <xs:documentation>可以设置等级的属性,这种属性可以随着等级而改变属性值。</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:decimals" use="optional" >
                        <xs:annotation><xs:documentation>属性初始值, int值.</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="level" type="xs:integer" use="optional" >
                        <xs:annotation><xs:documentation>属性的初始等级，默认"1"</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="levelEl" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                绑定一个等级类型的计算公式(el id), 必须是 level 类型的el. 属性通过这个el公式来计算属性的等级值。
                                如果没有设置这个公式，则设置属性的等级将没有意义。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeLevelInteger" >
        <xs:annotation>
            <xs:documentation>可以设置等级的属性,这种属性可以随着等级而改变属性值。</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:integer" use="optional" >
                        <xs:annotation><xs:documentation>属性初始值, int值.</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="level" type="xs:integer" use="optional" >
                        <xs:annotation><xs:documentation>属性的初始等级，默认"1"</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="levelEl" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                绑定一个等级类型的计算公式(el id), 必须是 level 类型的el. 属性通过这个el公式来计算属性的等级值。
                                如果没有设置这个公式，则设置属性的等级将没有意义。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeLimitInteger" >
        <xs:annotation>
            <xs:documentation>可以限制取值范围的属性，这种属性可以通过设置minValue,maxValue或绑定一个
                其它属性来限制当前属性的取值范围。
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:integer" use="optional" >
                        <xs:annotation><xs:documentation>属性初始值, int值.</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="minValue" type="xs:integer" use="optional" >
                        <xs:annotation><xs:documentation>最小值限制，int类型，如果设置了bindMinLimitAttribute则minValue将会被忽略</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="maxValue" type="xs:integer" use="optional" >
                        <xs:annotation><xs:documentation>最大值限制，int类型，如果设置了bindMaxLimitAttribute则maxValue将会被忽略</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="bindMinLimitAttribute" type="xs:string" use="optional" >
                        <xs:annotation><xs:documentation>bind NumberAttribute, 绑定一个属性"名称", 用这个属性的值来限制当前属性值的最小值。如果设置了这个值，则minValue的设置将会被忽略。</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="bindMaxLimitAttribute" type="xs:string" use="optional" >
                        <xs:annotation><xs:documentation>bind NumberAttribute, 绑定一个属性"名称", 用这个属性的值来限制当前属性值的最大值。如果设置了这个值，则maxValue的设置将会被忽略。</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeLong" >
        <xs:annotation>
            <xs:documentation>Long类型的Number属性</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:integer" use="optional" >
                        <xs:annotation><xs:documentation>属性初始值, long或int</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeRelateBoolean" >
        <xs:annotation>
            <xs:documentation>具有联动功能的Boolean属性</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="bool" use="optional" >
                        <xs:annotation><xs:documentation>属性初始值,如果属性设置了valueEl则这个数值可能会在运行时重新计算。</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="refVars" type="xs:string" use="optional" >
                        <xs:annotation><xs:documentation>
                            关联要引用的属性（名称），只有关联后才可以在参数valueEl中使用，并且角色也必须配置有引用的属性才可以。
                            格式："varName=attributeName,varName2=attributeName2,...", 示例："health=attributeHealth, mana=attributeMana"
                        </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="valueEl" type="xs:string" use="optional" >
                        <xs:annotation><xs:documentation>
                                填写一条表达式, 表达式的值必须返回Boolean类型，示例: "#{health > 0 && mana > 0}", 表达式中的参数必须在refVars中设置了引用。
                                并且需要确保角色同时配置有所引用的属性。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeString" >
        <xs:annotation>
            <xs:documentation>整数类型的属性</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:string" use="optional" >
                        <xs:annotation><xs:documentation>属性初始值, String类型</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeStringList">
        <xs:annotation>
            <xs:documentation>字符串集合</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation><xs:documentation>格式：“value1,value2,...”</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="duplication" type="bool" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                是否允许重复,默认情况下不允许存放重复元素, 比如已经有元素："apple,banana", 当再次添加元素"apple"时将会被忽略。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeVector2f">
        <xs:annotation>
            <xs:documentation>vector2f类型的属性</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation><xs:documentation>Vector2fAttribute类型，包含2个元素，格式：“x,y”</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeVector3f">
        <xs:annotation>
            <xs:documentation>vector3f类型的属性</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation><xs:documentation>Vector3fAttribute类型，包含3个元素，格式：“x,y,z”</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="attributeVector4f">
        <xs:annotation>
            <xs:documentation>vector4f类型的属性</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="attributeBase">
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation><xs:documentation>Vector4fAttribute类型，包含4个元素，格式：“x,y,z,w”</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="attributeBase">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:attribute name="name" type="xs:string" use="required" >
                    <xs:annotation>
                        <xs:documentation>
                            属性名称,每个属性都需要一个名称。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== guyue123/ly/ly-luoying-desktop/src/data/object/attribute.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name ../../../../ly-kernel/src/LuoYingSys/Data/meta/attribute.xsd'>
    
    <!--==========================================================================-->
    <!--标准属性
    属性用于配置到角色身上，一个角色可以同时拥有多个属性，这些属性可以绑定到任何其它模块或处理器上。

    说明1：属性id和名称都不能重复，当给角色配置具有相同id或名称的属性时，后载入的属性会替换先载入的。
    说明2：所有属性在绑定和引用的时候都是统一使用"属性名称"作为识别，只有在将属性配置给实体角色时才使用id。
    -->
    <!--==========================================================================-->
    
    <!--角色名字-->
    <attributeString id="attributeName" name="attributeName" />
    
    <!--角色性别: 这个属性用不同的数字(整数)来定义和区分不同的性别-->
    <attributeInteger id="attributeSex" name="attributeSex" value="0" />

    <!--角色种族: 这个属性用来存放角色的种族标识，用不同的数字来定义不同的种族,存放的值由具体实现去定义。--> 
    <attributeInteger id="attributeRace" name="attributeRace" value="0" />
    
    <!--判断一个角色是否为玩家-->
    <attributeBoolean id="attributePlayer" name="attributePlayer" />
    
    <!--死亡属性标记：1 ： 死亡， 0：没死亡. 注：角色是否死亡由这个参数直接判断，与“健康值”属性有联系，但不是由健康值直接判断。 -->
    <attributeRelateBoolean id="attributeDead" name="attributeDead" refVars="h=attributeHealth" valueEl="#{h<=0}" />

    <!--生物属性： 这个属性用来标记角色是否是生物，即有"生命迹象"的角色，1：表示生物; 0：表示非生物-->
    <attributeBoolean id="attributeBiology" name="attributeBiology" value="1" />
    
    <!--角色的等级, 这个属性在运行时存放角色的等级值。-->
    <attributeInteger id="attributeLevel" name="attributeLevel" value="1" />

    <!--角色升级功能开关, 只有属性为true时，角色才可以动态升级 -->
    <attributeBoolean id="attributeLevelUp" name="attributeLevelUp" value="1" />

    <!--当前角色可用的经验值-->
    <attributeInteger id="attributeXp" name="attributeXp" />
    
    <!--到达下一个等级角色需要的经验值-->
    <attributeInteger id="attributeXpNext" name="attributeXpNext" />
    
    <!--角色所在分组-->
    <attributeInteger id="attributeGroup" name="attributeGroup" />
    
    <!--角色所在队伍-->
    <attributeInteger id="attributeTeam" name="attributeTeam" />
    
    <!--视力:影响角色的侦察范围-->
    <attributeInteger id="attributeVision" name="attributeVision" value="30" />
    
    <!--移动速度倍率：1.0为原始速度,2.0为两倍速度,默认1.0-->
    <attributeFloat id="attributeMoveSpeed" name="attributeMoveSpeed" value="1.0" />
    
    <!--角色的质量:默认角色质量都是大于0的，即默认都为动态角色。 -->
    <attributeFloat id="attributeMass" name="attributeMass" value="60" />

    <!--定义角色是否可移动的-->
    <attributeBoolean id="attributeMovable" name="attributeMovable" value="1" />
    
    <!--定义角色是否是可转动的-->
    <attributeBoolean id="attributeRotatable" name="attributeRotatable" value="1" />
    
    <!--Essential属性: 这个属性用来标记角色是否是必要的，即使死亡后也不能移出场景, 一般任务角色要设置为true.-->
    <attributeBoolean id="attributeEssential" name="attributeEssential" />

    <!--是否自动AI,如果关闭AI功能，则角色将完全停止运行所有逻辑-->
    <attributeBoolean id="attributeAutoLogic" name="attributeAutoLogic" value="1" />
    
    <!--自动侦察敌人：这个属性值为1(true)时，角色打开自动侦察敌人的行为逻辑。-->
    <attributeBoolean id="attributeAutoAi" name="attributeAutoAi" value="1" />
    
    <!--目标属性： 这个属性用于存放角色的当前目标对象（角色的唯 一ID）-->
    <attributeLong id="attributeTarget" name="attributeTarget" />
    
    <!--这个属性用来存放角色当前跟随的目标-->
    <attributeLong id="attributeFollow" name="attributeFollow" />
    
    <!--角色的拥有者属性：这个属性用于存放角色的所有者（主人）,存放的是唯一id -->
    <attributeLong id="attributeOwner" name="attributeOwner" />
    
    <!--天赋点数属性，这个属性用于存放角色的天赋点数-->
    <attributeInteger id="attributeTalentPoints" name="attributeTalentPoints" />

    <!--实时健康值-->
    <attributeLimitInteger id="attributeHealth" name="attributeHealth" minValue="0" bindMaxLimitAttribute="attributeHealthMax" />
    <!--最高健康值:用于限制实时健康值，这个属性值会随等级而变化-->
    <attributeLevelInteger id="attributeHealthMax" name="attributeHealthMax" levelEl="elLevelAttrHealth" />
    
    <!--实时魔法值-->
    <attributeLimitInteger id="attributeMana" name="attributeMana" minValue="0" bindMaxLimitAttribute="attributeManaMax" />
    <!--最高魔法值: 用于限制实时魔法值，这个属性值会随等级而变化-->
    <attributeLevelInteger id="attributeManaMax" name="attributeManaMax" levelEl="elLevelAttrMana" />
    
    <!--物理攻击力-->
    <attributeLevelInteger id="attributeAttack" name="attributeAttack" levelEl="elLevelAttrAttack" />
    
    <!--魔法攻击力-->
    <attributeLevelInteger id="attributeMagicAttack" name="attributeMagicAttack" levelEl="elLevelAttrMagicAttack" />
    
    <!--物理防御力-->
    <attributeLevelInteger id="attributeDefence" name="attributeDefence" levelEl="elLevelAttrDefence" />
    
    <!--魔法防御力-->
    <attributeLevelInteger id="attributeMagicDefence" name="attributeMagicDefence" levelEl="elLevelAttrMagicDefence" />
    
    <!--健康值恢复速度: 定义每秒恢复多少点生命值-->
    <attributeLevelInteger id="attributeHealthRestore" name="attributeHealthRestore" levelEl="elLevelAttrHealthRestore" />
    
    <!--魔法值恢复速度: 定义每秒恢复多少点魔法值-->
    <attributeLevelInteger id="attributeManaRestore" name="attributeManaRestore" levelEl="elLevelAttrManaRestore" />
    
    <!--攻击速度: 定义攻击速度倍率，1.0为原始速度，-->
    <attributeLevelFloat id="attributeAttackSpeed" name="attributeAttackSpeed" levelEl="elLevelAttrAttackSpeed" />
    
    <!--施法速度:1.0为原始速度，2.0为双倍速度-->
    <attributeLevelFloat id="attributeMagicSpeed" name="attributeMagicSpeed" levelEl="elLevelAttrMagicSpeed" />
    
    <!--防御概率:[0.0~1.0], 1.0为百分百防御-->
    <attributeLevelFloat id="attributeDefenceRate" name="attributeDefenceRate" levelEl="elLevelAttrDefenceRate" />
    
    <!--躲闪概率:[0.0~1.0]，1.0为百分百躲闪-->
    <attributeLevelFloat id="attributeDuckRate" name="attributeDuckRate" levelEl="elLevelAttrDuckRate" />
    
    <!--鬼魅能力:[0.0~1.0] -->
    <attributeLevelFloat id="attributeGhostRate" name="attributeGhostRate" levelEl="elLevelAttrGhostRate" />
        
    <!--抗技能中断属性: [0.0~1.0], 防止技能被中断的概率，当为技能绑定这个属性之后，技能有一定概率防止被高优先级的其它技能中断-->
    <attributeFloat id="attributeResistInterruptRate" name="attributeResistInterruptRate" value="0.3"  />
    
    <!--武器槽位：这个参数定义角色默认支持的武器槽位,默认空，由不同的角色去配置。-->
    <attributeStringList id="attributeWeaponSlots" name="attributeWeaponSlots" />
    
    <!--角色的位置-->
    <attributeVector3f id="attributeLocation" name="attributeLocation" value="0,0,0" />

    <!--角色颜色-->
    <attributeColor id="attributeColor" name="attributeColor" value="1,1,1,1" />
    
    <!--用于控制角色的游戏消息的开关：当角色执行技能、使用物品等操作时会向游戏消息控制台发送消息。-->
    <attributeBoolean id="attributeMessage" name="attributeMessage" value="0" />
    
    <!--==========================================================================-->
    <!--基本属性打包-->
    <!--==========================================================================-->
    
    <attributeGroup id="attributeGroupBase" name="attributeGroupBase" 
                    attributes="attributeName,attributeBiology,attributeRace,attributeSex
    ,attributeLevel,attributeLevelUp,attributeXp,attributeXpNext,attributeGroup,attributeTeam,attributeVision,attributeMoveSpeed,attributeMass
    ,attributeDead,attributeMovable,attributeRotatable,attributeEssential,attributeAutoLogic,attributeAutoAi
    ,attributeTarget,attributeFollow,attributeOwner,attributeTalentPoints
    ,attributeHealthMax,attributeHealth,attributeManaMax,attributeMana
    ,attributeAttack,attributeMagicAttack,attributeDefence,attributeMagicDefence
    ,attributeHealthRestore,attributeManaRestore
    ,attributeAttackSpeed,attributeMagicSpeed
    ,attributeDefenceRate,attributeDuckRate,attributeGhostRate,attributeResistInterruptRate
    ,attributeWeaponSlots,attributeLocation,attributeColor,attributePlayer,attributeMessage
" />
    
    <!--==========================================================================-->
    <!--分类配置: 用于定义不同种族、性别等。 -->
    <!-- 注意：这里用继承，并替换值，属性名称不能改变, 要继承自父属性名称， 否则就是不同的属性了, 
        因属性在角色身上主要用名称来识别。-->
    <!--==========================================================================-->
    
    <!--生物定义：0：非生物；1：生物-->
    <!--生物：如人类兽人、狼、狗、野兽等可以活动的角色-->
    <!--非生物：如防御塔、宝箱、祭坛等非活动角色-->
    <attributeBoolean id="attributeBiologyNo" extends="attributeBiology" value="0" />
    <attributeBoolean id="attributeBiologyYes" extends="attributeBiology" value="1" />
    
    <!--角色种族定义: 0：未分类； 1：人类； 2：兽族 --> 
    <attributeInteger id="attributeRaceUnknow" extends="attributeRace" value="0" />
    <attributeInteger id="attributeRaceHuman" extends="attributeRace" value="1" />
    <attributeInteger id="attributeRaceOrc" extends="attributeRace" value="2" />
    
    <!--性别定义: 0: 未知性别; 1:女性; 2: 男性-->
    <attributeInteger id="attributeSexUnknow" extends="attributeSex" value="0" />
    <attributeInteger id="attributeSexFemale" extends="attributeSex" value="1" />
    <attributeInteger id="attributeSexMale" extends="attributeSex" value="2" />
    
    <!--定义角色是否是可移动的-->
    <attributeBoolean id="attributeMovableYes" extends="attributeMovable" value="1" />
    <attributeBoolean id="attributeMovableNo" extends="attributeMovable" value="0" />
    
    <!--定义角色是否是可转向的-->
    <attributeBoolean id="attributeRotatableYes" extends="attributeRotatable" value="1" />
    <attributeBoolean id="attributeRotatableNo" extends="attributeRotatable" value="0" />
    
    <!-- 角色质量，定义动态角色或静态角色 -->
    <attributeFloat id="attributeMassDynamic" extends="attributeMass" value="60" />
    <attributeFloat id="attributeMassStatic" extends="attributeMass" value="0" />
    
    <!--武器槽位: 人类女性武器槽位-->
    <attributeStringList id="attributeHumanFemaleWeaponSlot" extends="attributeWeaponSlots" 
                         value="slotSwordRightBack,slotSwordRightBack2,slotBowLeftBack,slotWandLeftBack" />
    
    <!--定义角色是否可动态升级-->
    <attributeBoolean id="attributeLevelUpYes" extends="attributeLevelUp" value="1" />
    <attributeBoolean id="attributeLevelUpNo" extends="attributeLevelUp"  value="0" />
    
    <!--==========================================================================-->
    <!--种族配置： 这些属性是直接配置给角色的。-->
    <!--==========================================================================-->
    
    <!--配置给：动态建筑物角色， 如：坦克、飞机、战车等可移动的等非生物类角色. -->
    <attributeGroup id="attributeDynamicBuildingGroup" name="attributeDynamicBuildingGroup"
