=== guyue123/ly/ly-luoying-desktop/bin/LuoYing/data/meta/item.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://luoying.huliqing.name"
           xmlns="http://luoying.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="./base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="itemTest" />
                <xs:element ref="itemAttribute" />
                <xs:element ref="itemBook" />
                <xs:element ref="itemMap" />
                <xs:element ref="itemSimple" />
                <xs:element ref="itemSkill" />
                <xs:element ref="itemState" />
                <xs:element ref="itemStateRemove" />
                <xs:element ref="itemSummon" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="itemTest">
        <xs:annotation>
            <xs:documentation>测试用</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="itemBase">
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="itemAttribute">
        <xs:annotation>
            <xs:documentation>消耗品，用于为指定角色补充属性值的物品</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="itemBase">
                    <xs:attribute name="attribute" type="xs:integer" use="required" >
                        <xs:annotation><xs:documentation>指定要操作的是哪一个属性ID</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="amount" type="xs:decimal" use="required" >
                        <xs:annotation><xs:documentation>指定补多少量,可正可负，正表示增加，负表示减少</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="itemBook">
        <xs:annotation>
            <xs:documentation>技能书, 使用后消耗技能书,并获得一个指定的技能</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="itemBase">
                    <xs:attribute name="skill" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>指定要学习的技能ID</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="itemMap">
        <xs:annotation>
            <xs:documentation>地图物品，点击后可打开地图</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="itemBase">
                    <xs:attribute name="image" use="optional" type="xs:string">
                        <xs:annotation>
                            <xs:documentation>指定一个地图图片，格式: "Interface/map/xxx.jpg"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="locations" use="optional" type="xs:string">
                        <xs:annotation>
                            <xs:documentation>格式： "id|x|y|enabled|gameId|icon", 
                                id为地图点名称;
                                x,y为地图上的坐标位置,取值[0.0~1.0]; 
                                enabled是否激活这个位置点,取值: 0/1, 0或其它值表示未开启，1表示开启
                                gameId为连接到一个游戏场景(game.xml), 可不设置;
                                icon可为位置点指定一个特别的图标，可不设置。
                                示例: "place1|0.2|0.5|1|treasureGame|Interface/map/place.jpg"
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="mapSize" type="xs:decimal" use="optional" >
                        <xs:annotation>
                            <xs:documentation>地图大小倍率，默认1.0</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="mapAlpha" type="xs:decimal" use="optional" >
                        <xs:annotation>
                            <xs:documentation>地图透明度，默认1.0</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="locationIcon" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                默认的位置点图标,如: "Interface/map/location.png", 必须是完整路径，所有在locations中未指定图标的
                                位置点将使用这个图标作为默认图标。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="locationSize" type="xs:decimal" use="optional" >
                        <xs:annotation>
                            <xs:documentation>地图位置点图标大小倍率，默认1.0</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="baseIconPath" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>位置点图标的基本路径，如果指定了这个基本路径，则locations中的图标不需要再配置上完整的
                            图标路径。示例："Interface/map/"
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="flipVertical" type="bool" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                是否反转位置点上的垂直位置。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="itemSimple">
        <xs:annotation>
            <xs:documentation>普通物品，没有任何属性的物品</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="itemBase"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="itemSkill">
        <xs:annotation>
            <xs:documentation>消耗物品来使用一个技能，示例：如使用复活卷轴,在使用这个物品的时候会调用一个技能来让角色执行。</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="itemBase">
                    <xs:attribute name="skill" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>默认要使用的技能</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="itemState">
        <xs:annotation>
            <xs:documentation>可让角色获得某些状态的物品</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="itemBase">
                    <xs:attribute name="states" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>指定要获得的状态列表，格式如："stateId,stateId,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="itemStateRemove">
        <xs:annotation>
            <xs:documentation>可用于删除角色身上某些状态的物品</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="itemBase">
                    <xs:attribute name="states" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>要移除的状态列表，格式如："stateId,stateId,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="itemSummon">
        <xs:annotation>
            <xs:documentation>可用于召唤角色的物品</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="itemBase">
                    <xs:attribute name="actorId" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>
                                指定要召唤的角色ID
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="summonTotal" type="xs:integer" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                指定要召唤多少个角色,默认：1
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="copyAttributesFromSource" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>
                                设置要从source（召唤者）同步的属性值，这是个属性名称列表，当召唤后，被召唤的角色的这些属性的值将从召唤者身上获取。
                                比如等级属性，分组属性，以便被召唤后的角色与召唤者有一样的等级和分组, 示例："attributeGroup,attributeLevel"
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="linkAttributesToSource" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>
                                设置要将被召唤者的属性的值连接到召唤者的属性名称。当召唤后，被召唤的角色的这些属性将指向召唤者的entityId.所以这些属性必须是NumberAttribute类型。
                                比如attributeFollow,attributeOwner属性，指向跟随者和拥有者，示例："attributeOwner,attributeFollow"
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="itemBase">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:attribute name="icon" ref="icon" use="required" />
                <xs:attribute name="checkEl" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>绑定或直接填写一条SBooleanEl, 这条El用来判断s角色是否可以使用这件物品，示例：#{!s.attributeDead}</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="effects" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>
                        效果,格式: "effect1,effect2,...",这些效果会在执行时立即应用在角色身上。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="sounds" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>
                        声效,格式: "sound1,sound2,...",这些声音会在执行时立即播放,在角色的位置。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute ref="total" use="optional" />
                <xs:attribute ref="tradeInfos" use="optional" />
                <xs:attribute name="deletable" type="bool" use="optional">
                    <xs:annotation>
                        <xs:documentation>物品是否可删除</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="sellable" type="bool" use="optional">
                    <xs:annotation>
                        <xs:documentation>物品是否可以进行出售</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="localObject" type="bool" use="optional" >
                    <xs:annotation>
                        <xs:documentation>
                            是否为本地物体,对于本地物体在使用的时候不需要把事件传递到服务端或客户端。比如：客户端或服务端在打开地图
                            的时候是不需要把事件传递到其它客户端或服务端的。localObject这是一种特殊的物品，只通过本地handler执行，
                            所以使用后物品数量不会实时同步到其它客户端。需要注意这一点。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
</xs:schema>

=== guyue123/ly/ly-luoying-desktop/src/data/object/item.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name ../../../../ly-kernel/src/LuoYing/Data/meta/item.xsd'>
    
    <!-- ========================================================================= -->
    <!--基本配置-->
    <!-- ========================================================================= -->
    
    <!--物品基类-->
    <itemSimple id="itemBase" checkEl="elItemSimpleUse" />
    
    <!--药水类-->
    <itemAttribute id="itemTonicBase" extends="itemBase" effects="effectRandomFire" />
    
    <!--技能书 -->
    <itemBook id="itemBookBase" extends="itemBase" effects="effectLearnSkill"/>
    
    <!--召唤卷轴-->
    <itemSkill id="itemScrollBase" extends="itemBase" />
    
    <!--召唤类物品的基本设置-->
    <itemSummon id="itemSummonBase" extends="itemBase" copyAttributesFromSource="attributeGroup,attributeLevel" linkAttributesToSource="attributeOwner,attributeFollowTarget" />
    
    <!-- ========================================================================= -->
    <!--种族类限制物品-->
    <!-- ========================================================================= -->
    
    <!--技能书：人类种族 -->
    <itemBook id="itemBookHumanBase" extends="itemBookBase" checkEl="elItemBookHuman" />
    
    <!-- ========================================================================= -->
    <!--特殊物品-->
    <!-- ========================================================================= -->
    
    <!--for test-->
    <itemTest id="item000" extends="itemBase" icon="Interface/item/book.png" /> 
    
    <!--Gold-->
    <itemSimple id="itemGold" extends="itemBase" icon="Interface/item/gold.png" tradeInfos="itemGold|1" sellable="1" />
    
    <!--复活卷轴-->
    <itemSkill id="itemScrollLife" extends="itemBase" icon="Interface/item/scroll_life.png" skill="skillShotReborn" tradeInfos="itemGold|200" />
    
    <!-- ========================================================================= -->
    <!--技能书籍-->
    <!-- ========================================================================= -->
    
    <!--书：野兽召唤术:不再使用--> 
    <!--<itemBook id="itemBook005" extends="itemBookBase" icon="Interface/item/book_blue.png" skill="skillSummon" />--> 

    <!--书：闪电箭-->
    <itemBook id="itemBook006" extends="itemBookHumanBase" icon="Interface/item/book_green.png" skill="skillLightningShot" /> 
    <!--书：星光传送术-->
    <itemBook id="itemBook007" extends="itemBookHumanBase" icon="Interface/item/book_green.png" skill="skillBack" tradeInfos="itemGold|250" /> 
    <!--书：落樱飞舞-->
    <itemBook id="itemBook008" extends="itemBookHumanBase" icon="Interface/item/book_green.png" skill="skillDanceSakura" tradeInfos="itemGold|500" /> 
    <!--书: 寒冰箭-->
    <itemBook id="itemBook009" extends="itemBookHumanBase" icon="Interface/item/book_green.png" skill="skillIceShot" tradeInfos="itemGold|800" /> 
    <!--书: 二刀流冲击波-->
    <itemBook id="itemBook010" extends="itemBookHumanBase" icon="Interface/item/book_green.png" skill="skillDualSwordWave" tradeInfos="itemGold|800" /> 
    
    <!-- ========================================================================= -->
    <!--召唤类物品-->
    <!-- ========================================================================= -->
    
    <!--召唤：狼-->
    <itemSkill id="itemScrollWolf" extends="itemScrollBase" icon="Interface/item/scroll_wolf.png" skill="skillSummonWolf" tradeInfos="itemGold|200" />
    <!--召唤：熊-->
    <itemSkill id="itemScrollBear" extends="itemScrollBase" icon="Interface/item/scroll_bear.png" skill="skillSummonBear" tradeInfos="itemGold|200" />
    <!--召唤：蝎子-->
    <itemSkill id="itemScrollScorpion" extends="itemScrollBase" icon="Interface/item/scroll_scorpion.png" skill="skillSummonScorpion" tradeInfos="itemGold|200" />
    <!--召唤：迅猛龙-->
    <itemSkill id="itemScrollRaptor" extends="itemScrollBase" icon="" skill="skillSummonRaptor" tradeInfos="itemGold|400"  />
    <!--召唤：雷龙-->
    <itemSkill id="itemScrollTrex" extends="itemScrollBase" icon="" skill="skillSummonTrex"  tradeInfos="itemGold|600" />
    <!--召唤：蜘蛛-->
    <itemSkill id="itemSpiderSpawn" extends="itemScrollBase" icon="Interface/item/spawn.png" skill="skillSummonSpider"  />
    <!--召唤：古柏树根-->
    <itemSkill id="itemTreeStump" extends="itemScrollBase" icon="Interface/item/treeStump.png" skill="skillSummonGb" tradeInfos="itemGold|200" />
    
    <!--召唤：防御塔-->
    <itemSummon id="itemTower" extends="itemSummonBase" icon="Interface/item/tower_fire.png" actorId="actorTower" tradeInfos="itemGold|300" />
    <itemSummon id="itemTowerStone" extends="itemSummonBase" icon="Interface/item/tower_stone.png" actorId="actorTowerStone" tradeInfos="itemGold|300" />
    <itemSummon id="itemTowerSnow" extends="itemSummonBase" icon="Interface/item/tower_snow.png" actorId="actorTowerSnow" tradeInfos="itemGold|300" />
    
    <!-- ========================================================================= -->
    <!--药品类\增益类-->
    <!-- ========================================================================= -->
    
    <!--红瓶和蓝瓶-->
    <itemAttribute id="itemTonicRed" extends="itemTonicBase"  icon="Interface/item/tonic_red.png" attribute="attributeHealth" amount="200" tradeInfos="itemGold|50" />
    <itemAttribute id="itemTonicBlue" extends="itemTonicBase" icon="Interface/item/tonic_blue.png" attribute="attributeMana" amount="200" tradeInfos="itemGold|50" />
    
    <!--攻击、施法速度药水(attack speed)-->
    <itemState id="itemASTonic" extends="itemTonicBase" icon="Interface/item/tonic_yellow.png" states="stateSpeedUpAS" tradeInfos="itemGold|300" />
    
    <!--风中劲草-->
    <itemState id="itemHerb" extends="itemTonicBase" icon="Interface/item/grass.png" states="stateWindWalk" tradeInfos="itemGold|100" />

    <!--解除中毒状态: 解毒草用-->
    <itemStateRemove id="itemDetoxifyGrass" extends="itemBase"  icon="Interface/item/leaf.png" states="stateScorpionVenom" effects="effectTonic" tradeInfos="itemGold|20" />
    
    <!--==========================================================================-->
    <!-- 任务物品 -->
    <!--==========================================================================-->
    
    <!--蜘蛛爪-->
    <itemSimple id="itemSpiderClaw" extends="itemBase" icon="Interface/item/claw.png" sellable="0" />
    
    <!--==========================================================================-->
    <!-- 地图 -->
    <!--==========================================================================-->
    
    <!--落樱大陆地图-->
    <itemMap id="itemMapWorld" extends="itemBase" icon="Interface/map/map_world_icon.jpg" deletable="0" localObject="1"
            image="Interface/map/map_world.jpg" locationSize="0.5" flipVertical="1"
                baseIconPath="Interface/map/loc/"
                locations="start|0.86|0.63|1|gameStoryTreasure|star.png
, city1|0.36|0.38|1|gameStoryGb|town2.png
, city2|0.46|0.29|1|gameStoryGuard|citadel1.png
, city3|0.51|0.40|1|gameSurvival|city2.png
, city4|0.65|0.41|0||citadel2.png
, village1|0.17|0.49|0||village1.png
, village2|0.32|0.51|0||village1.png
, village3|0.72|0.42|0||village1.png
, village4|0.77|0.57|0||village1.png
, farmField1|0.29|0.55|0||farmField.png
, farmField2|0.35|0.55|0||farmField.png
, farmField3|0.38|0.57|0||farmField.png
, chiefCamp1|0.30|0.07|0||chiefCamp.png
, chiefCamp2|0.95|0.12|0||chiefCamp.png
, cave1|0.44|0.05|0||cave.png
, cave2|0.85|0.05|0||cave.png
, ruin1|0.93|0.37|0||ruin.png
, camp1|0.40|0.72|0||camp.png
, camp2|0.56|0.70|0||camp.png
, camp3|0.68|0.58|0||camp.png
, camp4|0.86|0.50|0||camp.png
, camp5|0.92|0.28|0||camp.png
, camp6|0.82|0.17|0||camp.png
, camp7|0.59|0.14|0||camp.png
, camp8|0.45|0.13|0||camp.png
" />
    
<!--    落樱小岛
    <itemMap id="itemMapIsland" icon="Interface/map/map_island_icon.jpg"  deletable="0" localObject="1" />-->
</root>
