=== guyue123/ly/ly-luoying-desktop/bin/LuoYing/data/meta/logic.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://luoying.huliqing.name"
           xmlns="http://luoying.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="./base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="logicBase" />
                <xs:element ref="logicFight" />
                <xs:element ref="logicFollow" />
                <xs:element ref="logicNotify" />
                
                <!--remove20161121-->
                <!--<xs:element ref="logicPlayer" />-->
                
                <xs:element ref="logicPosition" />
                <xs:element ref="logicSearchEnemy" />
                <xs:element ref="logicDefend" />
                <xs:element ref="logicIdle" />
                <xs:element ref="logicShop" />
                <xs:element ref="logicAttributeChange" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="logicShop">
        <xs:annotation>
            <xs:documentation>
                商店类逻辑，该逻辑会每隔一段时间给角色进货。以补充商店类角色的货源,
                一般配置给商店类角色。这类逻辑不需要太频繁，默认频率20(interval)秒。
                即interval定义了进货时间间隔。
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase">
                    <xs:attribute name="items" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>format: "item|maxCount,item|maxCount,item|maxCount,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="stockSpeed" type="xs:decimal" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                进货速度，如：1.0 表示每秒进货一件（每件未达到maxCount的商品各进货一件）
                                如:0.1 则表示10秒进货一件，依此类推;
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="initStock" type="bool" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                是否初始化时把货物进满,默认true.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="logicDefend">
        <xs:annotation>
            <xs:documentation>
                角色的防守及躲闪,一般频率不要太高。
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase">
                    <xs:attribute name="defendRateAttribute" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定使用哪一个角色属性作为防守概率。概率值范围[0.0~1.0]</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="duckRateAttribute" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定使用哪一个角色属性作为躲闪概率。概率值范围[0.0~1.0]</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="listenAttributes" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                指定要监听哪些属性，即当这些属性被目标击中时会把目标角色列为敌人。
                                格式，如: "attributeHealth,..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="listenSkillTypes" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                指定要监听哪些战斗技能，当目标角色执行这些类型的技能时，当前角色会偿试进行防守或躲闪,格式: "skillTag1,skillTag2,..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="defendSkillTypes" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定要使用哪些“防守”技能来防守敌人,格式: "skillTag1,skillTag2,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="duckSkillTypes" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定要使用哪些“躲闪”技能来躲闪敌人的攻击,格式: "skillTag1,skillTag2,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="logicAttributeChange">
        <xs:annotation>
            <xs:documentation>
                用于改变角色属性值的逻辑，计算公式：targetAttributeAddValue = value * bindFactorAttribute * interval
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase">
                    <xs:attribute name="value" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>改变的值，该值表示每秒要改变的目标属性的值。</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="applyAttribute" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定要改变的是哪一个属性</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="bindFactorAttribute" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>使用另一个属性作为影响因数。</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="logicPosition">
        <xs:annotation>
            <xs:documentation>位置移动行为,让目标往一个位置移动.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase">
                    <xs:attribute name="runAction" type="xs:string" use="required">
                        <xs:annotation><xs:documentation>指定一个RunAction</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="position" type="xs:string" use="optional">
                        <xs:annotation><xs:documentation>目标地点，如："0,0,0"</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="nearest" type="xs:decimal" use="optional">
                        <xs:annotation><xs:documentation>跟随的最近距离</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <!--remove20161121-->
<!--    <xs:element name="logicPlayer">
        <xs:annotation>
            <xs:documentation>
                针对player类型的逻辑,特别去掉了idle行为。
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase">
                    <xs:attribute name="fightAction" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定一个FightAction</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>-->
    
    <xs:element name="logicNotify">
        <xs:annotation>
            <xs:documentation>
                这是一个通知逻辑，若当角色存在目标敌人时，会通知周围一定范围内的友军单位进行攻击目标，
比如当前角色受到攻击时，会通知同伴友军进行攻击目标。具体逻辑：
 1.当前角色存在目标, 该目标必须是敌方,该目标未死亡
 2.该逻辑会在当前角色周围一定范围内（可设置）查找还没有目标的友军单位。
 3.通过设置可强制周围友军将目标都锁定在与当前角色相同的目标上,即使友军已经存在目标。
注意:该逻辑不应该随便滥用,一般只用在主角,或敌军主力,队长,侦察兵之类,随便滥用会造成循环调用和冲突,资源浪费.
这个逻辑的频率可以不用太高.一般应该高于或等于1秒.如果需要在某一方使用多个当前逻辑,则建议最多只让其中一个逻辑的force属性
设置为true就可以,避免logicNotify之间的冲突.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase">
                    <xs:attribute name="distance" type="xs:decimal" use="optional">
                        <xs:annotation>
                            <xs:documentation>设置要通知的范围,不应该小于或等于0,否则没有意义.默认15</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="logicSearchEnemy">
        <xs:annotation>
            <xs:documentation>搜查敌人的逻辑,给角色添加这个逻辑来自动查找敌人。</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase">
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="logicIdle">
        <xs:annotation>
            <xs:documentation>
                空闲逻辑
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase">
                    <xs:attribute name="idleSimpleAction" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定一个普通的idle行为</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="idlePatrolAction" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定一个巡逻idle行为</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="patrolCheckEl" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>SBooleanEl, 指定角色在什么状态下使用idlePatrolAction,默认情况下idleLogic只使用idleSimpleAction</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="logicFollow">
        <xs:annotation>
            <xs:documentation>
                跟随逻辑
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase">
                    <xs:attribute name="bindFollowAttribute" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>NumberAttribute, 绑定角色的follow目标属性，这个属性存放当前需要跟随的目标对象的唯一ID。</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="followAction" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定一个跟随行为</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="minFollow" type="xs:decimal" use="optional">
                        <xs:annotation>
                            <xs:documentation>跟随距离的近点,默认3, 该值小于maxFollow和distanceLimit</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="maxFollow" type="xs:decimal" use="optional">
                        <xs:annotation>
                            <xs:documentation>跟随距离的远点,默认7,该值小于distanceLimit并大于minFollow</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="logicFight">
        <xs:annotation>
            <xs:documentation>
                战斗类角色，包含各类NPC，怪物，炮塔等等
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase">
                    <xs:attribute name="fightAction" type="xs:string" use="required">
                        <xs:annotation><xs:documentation>关联一个FightAction</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="bindAiAttribute" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                BooleanAttribute, 绑定角色的Ai属性，这个属性将用于控制当前逻辑的打开或关闭，默认为开</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="logicBase">
        <xs:annotation>
            <xs:documentation>抽象基类,不要直接使用，只用于被继承。</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="logicBase"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="logicBase">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:attribute name="interval" type="xs:decimal" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            指定逻辑执行时间间隔，单位秒，指定为0，表示该逻辑将尽可能快的执行。
                            指定为1，表示每一秒执行一次逻辑,默认1.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="enabledCheckEl" type="xs:string" use="required">
                    <xs:annotation><xs:documentation>STBooleanEl, 绑定一个el用来判断是否打开当前逻辑。</xs:documentation></xs:annotation>
                </xs:attribute>
                <xs:attribute name="bindTargetAttribute" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>NumberAttribute, 绑定角色的“目标”属性，这个属性存放了角色的当前目标对象的唯一id.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="bindViewAttribute" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>NumberAttribute, 绑定角色的视角范围属性，这个属性的值定义了角色可以看多远，决定了寻敌范围。</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="enemyCheckEl" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>STBooleanEl, 用于判断一个目标是否为敌人</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
</xs:schema>

=== guyue123/ly/ly-luoying-desktop/src/data/object/logic.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name ../../../../ly-kernel/src/LuoYing/Data/meta/logic.xsd'>
    
    <!-- ========================================================================== -->
    <!-- Base-->
    <!-- ========================================================================= -->

    <!--逻辑基类，所有逻辑都继承这个设置, 默认逻辑频率1.0秒，子设置根据实际情况设置-->
    
    <!--注：enabledCheckEl属性很重要，这个作为逻辑的开关，大部分情况下，角色必须是“活着的”才可以执行逻辑, 特别是
        一些特殊的可以改变角色属性的逻辑, 例如：可以改变角色健康值的逻辑，如果在角色死亡之后还运行，则可能让角色重新
        活起来。
    -->
    <logicBase id="logicBase" interval="1"
               enabledCheckEl="elActorUndeadCheck"
               bindTargetAttribute="attributeTarget" 
               bindViewAttribute="attributeVision" 
               enemyCheckEl="elActorEnemyCheck" />

    <!--战斗类逻辑: bindAiAttribute用于作为AI逻辑开关-->
    <logicFight id="logicFightBase" extends="logicBase" bindAiAttribute="attributeAutoAi" />
    
    <!--空闲类逻辑-->
    <logicIdle id="logicIdleBase" extends="logicBase" patrolCheckEl="#{!s.attributePlayer && s.attributeFollow <= 0}" />
    
    <!--通知类-->
    <logicNotify id="logicNotifyBase" extends="logicBase" />
    
    <!--侦察敌人的逻辑-->
    <logicSearchEnemy id="logicSearchEnemyBase" extends="logicBase" interval="2" />
    
    <!--商店逻辑：频率不用太高-->
    <logicShop id="logicShopBase" extends="logicBase" interval="30" />

    <!-- ========================================================================== -->
    <!-- Common -->
    <!-- ========================================================================= -->
    
    <!--默认的搜寻敌人的逻辑-->
    <logicSearchEnemy id="logicSearchEnemy" extends="logicSearchEnemyBase" />
    
    <!--默认的防守及躲闪逻辑-->
    <logicDefend id="logicDefend" interval="5" extends="logicBase" defendRateAttribute="attributeDefenceRate" duckRateAttribute="attributeDuckRate" 
                      listenAttributes="attributeHealth" listenSkillTypes="fight" defendSkillTypes="defend" duckSkillTypes="duck" />
    <!--空闲行为-->
    <logicIdle id="logicPatrol" extends="logicIdleBase" interval="5" idleSimpleAction="actionDynamicIdle" idlePatrolAction="actionPatrolIdle" />
    
    <!-- 动态战斗逻辑: 能够移动、战斗、跟随等的角色逻辑。如：人物，怪兽 -->
    <logicFight id="logicDynamicFight" extends="logicFightBase" fightAction="actionDynamicFight" />

    <!-- 静止类战斗逻辑：能够战斗但不能移动和转动的角色。如：防御塔，静止类武器等 -->
    <logicFight id="logicStaticFight" extends="logicFightBase" fightAction="actionStaticFight" />
    
    <!-- 跟随目标的逻辑 -->
    <logicFollow id="logicFollow" extends="logicBase" bindFollowAttribute="attributeFollow" followAction="actionFollow" />

    <!--通知逻辑-->
    <logicNotify id="logicNotify" extends="logicNotifyBase" />
    <logicNotify id="logicNotifyForce" extends="logicNotifyBase" />
    
    <!-- 向目标位置移动的逻辑 -->
    <logicPosition id="logicPosition" extends="logicBase" runAction="actionRun" />
    
   <!-- ==================================================================== -->
   <!-- 特定角色逻辑-->
   <!-- ==================================================================== -->
    
    <!--注：给商店逻辑配置一定的金币，这样当出售东西给商店时，商店才有钱可以购买玩家的商品-->
    
    <!--宝箱: 商店逻辑-->
    <logicShop id="logicShopTreasure" extends="logicShopBase" items="itemGold|10000,itemTonicRed|10,itemTonicBlue|10
,itemHerb|5,itemDetoxifyGrass|5,itemScrollLife|5,itemBook007|1" stockSpeed="1" />
    
<!--    <logicShop id="logicShopTreasure" extends="logicBase" items="itemTonicRed|10,itemTonicBlue|10,itemHerb|5,itemDetoxifyGrass|5
,itemGold|1000    
,itemScrollLife|5
,itemBook007|1
,skinEar004|1,skinBlinder001|1,skinMouthmask001|1,skinHorn001|1
,weaponSword001|1,weaponSword001L|1,weaponSword002,weaponSword002L,weaponSword003,weaponSword003L
,weaponBow001,weaponWand000" stockSpeed="0.1" />-->

    <!--杰米: 商店逻辑-->
    <logicShop id="logicShopJaime" extends="logicShopBase" items="itemGold|10000,itemTonicRed|10,itemTonicBlue|10,itemHerb|5,itemBook009|1" stockSpeed="1" />
    
    <!--用于黑暗祭坛,让角色生命恢复及魔法恢复更快-->
    <logicAttributeChange id="logicIncreaseAltarLife" extends="logicBase" value="10" applyAttribute="attributeHealth" bindFactorAttribute="attributeHealthRestore" interval="3" />
    
</root>
