=== guyue123/ly/ly-luoying-desktop/bin/LuoYing/data/meta/skin.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://luoying.huliqing.name"
           xmlns="http://luoying.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="./base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="skinOutfit" />
                <xs:element ref="skinWeapon" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="skinOutfit">
        <xs:annotation>
            <xs:documentation>
                基本skin,如：皮肤，装备等
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="baseSkin">
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="skinWeapon">
        <xs:annotation>
            <xs:documentation>
                武器装备
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="baseSkin">
                    <xs:attribute name="weaponType" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>
                                指定一个武器类型，格式："weaponType", 如："rightSword", 参考: define.xml中weaponType的定义 
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="slots" type="xs:integer" use="required" >
                        <xs:annotation>
                            <xs:documentation>
                                设置武器支持的槽位列表,格式如："slot1,slot2,...",
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="baseSkin">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:attribute name="icon" ref="icon" use="required" />
                <xs:attribute name="file" ref="file" use="required" />
                <xs:attribute name="baseSkin" type="bool" use="optional" >
                    <xs:annotation>
                        <xs:documentation>是否为基本破肤</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="parts" use="required" >
                    <xs:annotation>
                        <xs:documentation>
                            皮肤部位定义，see define.xml => defineSkinType,  格式 : "skinPart1,skinPart2,..."
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="conflictParts" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            排斥的目标skinPart，格式："skinPart1,skinPart2,...",一般情况下，当一个skin添加到角色身上时，目标角色身上的
                            相同部位的皮肤会脱下来，即同一个类型的skin不可能同时添加到角色身上.而conflictParts可以指定额外的排斥部位。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="bindBone" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>
                            如果指定了一个骨头名称，则skin将会被绑定到该骨头上,否则将直接被绑定到目标根节点。
                            注：对于使用bindBone的skin模型必须在blender导出时使用obj格式，不能使用ogre格式导出。
                            否则在绑定到角色身上时会发生错位。对于静态类的skin模型（即没有动画、不受权重影响的模型）
                            直接绑定到骨头节点上性能比较好。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="localLocation" type="xs:stirng" use="optional">
                    <xs:annotation><xs:documentation>skin添加到目标时的本地变换，格式："x,y,z"</xs:documentation></xs:annotation>
                </xs:attribute>
                <xs:attribute name="localRotation" type="xs:stirng" use="optional">
                    <xs:annotation><xs:documentation>skin添加到目标时的本地旋转(弧度)，格式："x,y,z"</xs:documentation></xs:annotation>
                </xs:attribute>
                <xs:attribute name="localScale" type="xs:stirng" use="optional">
                    <xs:annotation><xs:documentation>skin添加到目标时的本地缩放，格式："x,y,z"</xs:documentation></xs:annotation>
                </xs:attribute>
                <xs:attribute name="applyAttributes" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>
                            指定要应用到目标角色上的属性，格式："attribute|value",多个设置使用半角逗号分隔。
                            示例："attributeDefence|50,attributeMagicDefence|30", 表示物理防御+50，魔法防御+30
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="checkEl" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>绑定或直接填写一条SBooleanEl, 这条El用来判断source角色是否可以使用这件装备，示例：#{!s.attributeDead}</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="sounds" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>声效,格式:"sound1,sound2,..."</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute ref="mat" use="optional" />
                <xs:attribute ref="total" use="optional" />
                <xs:attribute ref="tradeInfos" use="optional" />
                <!--<xs:attribute name="cost" ref="cost" use="optional" />-->
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
</xs:schema>

=== guyue123/ly/ly-luoying-desktop/bin/LuoYing/data/skin_weapon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
skinType => 0:body; 1:armor 
skinPart => 0:ear;1:eyeL;2:eyeR;3:face;4:foot;5:hair;6:hand;7:lowerBody;8:upperBody; 
-->

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name meta/skin.xsd'>
    
    <!-- =========================================================================-->
    <!--基本定义-->
    <!-- =========================================================================-->
    
    <!--人类武器装备: 只有人类种族才可以使用的装备-->
    <skinOutfit id="weaponHumanBase" checkEl="elSkinHuman" />
    
    <!-- =========================================================================-->
    <!--人类武器分类定义-->
    <!-- =========================================================================-->
    
    <!--右手剑-->
    <skinWeapon id="weaponHumanRightSwordBase" extends="weaponHumanBase" 
                parts="rightHandWeapon" weaponType="rightSword" mat="metal" 
                bindBone="weapon.R" localLocation="0,0,0" localRotation="0,0,0" sounds="soundDrawSword" 
                slots="slotSwordLeftBack,slotSwordLeftBack2,slotSwordRightBack,slotSwordRightBack2,slotSwordLeftWaist,slotSwordLeftWaist2" />
    
    <!--左手剑-->
    <skinWeapon id="weaponHumanLeftSwordBase" extends="weaponHumanRightSwordBase" 
                parts="leftHandWeapon" weaponType="leftSword" mat="metal" 
                bindBone="weapon.L" localLocation="0,0,0" localRotation="0,3.14159265,0" />

    <!--弓-->
    <skinWeapon id="weaponHumanBowBase" extends="weaponHumanBase" 
                parts="leftHandWeapon,rightHandWeapon" weaponType="bow"
                bindBone="weapon.L" localRotation="0,0,0" localLocation="0,0,0"
                mat="wood" slots="slotBowLeftBack" sounds="soundDrawBow" />

    <!--魔杖-->
    <skinWeapon id="weaponHumanWandBase" extends="weaponHumanBase" 
                parts="leftHandWeapon,rightHandWeapon" weaponType="wand" 
                bindBone="weapon.R" localRotation="0,0,0" localLocation="0,0,0"
                mat="wood" slots="slotWandLeftBack" sounds="soundDressOutfit2" />
    
    <!--魔法书：暂未开放-->
    <skinWeapon id="weaponHumanBookBase" extends="weaponHumanBase" 
                parts="leftHandWeapon,rightHandWeapon" weaponType="unknow" 
                bindBone="weapon.L" mat="" localRotation="0,0,0" localLocation="0,0,0"
                sounds="" />
    
    <!--=====================================================================-->
    <!--虚拟的武器，无实物模型,用于所有无实际武器的角色。-->
    <!--=====================================================================-->
    
    <!--虚拟一把右手剑-->
    <skinWeapon id="weaponMockRightSword" parts="rightHandWeapon" weaponType="rightSword" mat="metal" sounds="soundDrawSword" />
    <!--虚拟一把右手剑（木）-->
    <skinWeapon id="weaponMockRightWoodSword" parts="rightHandWeapon" weaponType="rightSword" mat="wood" sounds="soundDrawSword" />
    <!--虚拟一动物爪子-->
    <skinWeapon id="weaponMockAnimalClaw" parts="leftHandWeapon,rightHandWeapon" weaponType="leftClaw,rightClaw" mat="calcium" sounds="soundDrawSword" />
    
    <!-- ====================================================================-->
    <!--实质武器:刀，剑-->
    <!-- ====================================================================-->
    
    <skinWeapon id="weaponSword000"  extends="weaponHumanRightSwordBase" cost="0"
                icon="Models/weapon/sword/sword000.png" file="Models/weapon/sword/sword000.j3o" 
                applyAttributes="attributeAttack|10,attributeMagicAttack|5" />
    <skinWeapon id="weaponSword000L" extends="weaponHumanLeftSwordBase" cost="0"
                icon="Models/weapon/sword/sword000.png" file="Models/weapon/sword/sword000.j3o"
                applyAttributes="attributeAttack|5,attributeMagicAttack|2" />
    
    <skinWeapon id="weaponSword001"  extends="weaponHumanRightSwordBase" cost="1200"
                icon="Models/weapon/sword/sword001.png" file="Models/weapon/sword/sword001.j3o"
                applyAttributes="attributeAttack|15,attributeMagicAttack|7" />
    <skinWeapon id="weaponSword001L" extends="weaponHumanLeftSwordBase" cost="1200"
                icon="Models/weapon/sword/sword001.png" file="Models/weapon/sword/sword001.j3o" 
                applyAttributes="attributeAttack|10,attributeMagicAttack|5" />
    
    <skinWeapon id="weaponSword002"  extends="weaponHumanRightSwordBase" cost="1400"
                icon="Models/weapon/sword/sword002.png" file="Models/weapon/sword/sword002.j3o" 
                applyAttributes="attributeAttack|20,attributeMagicAttack|8" />
    <skinWeapon id="weaponSword002L" extends="weaponHumanLeftSwordBase" cost="1400"
                icon="Models/weapon/sword/sword002.png" file="Models/weapon/sword/sword002.j3o"
                applyAttributes="attributeAttack|15,attributeMagicAttack|6" />
    
    <skinWeapon id="weaponSword003"  extends="weaponHumanRightSwordBase" cost="1600"
                icon="Models/weapon/sword/sword003.png" file="Models/weapon/sword/sword003.j3o" 
                applyAttributes="attributeAttack|25,attributeMagicAttack|10" />
    <skinWeapon id="weaponSword003L" extends="weaponHumanLeftSwordBase" cost="1600"
                icon="Models/weapon/sword/sword003.png" file="Models/weapon/sword/sword003.j3o"
                applyAttributes="attributeAttack|20,attributeMagicAttack|8" />
    
    <!-- ====================================================================-->
    <!--实质武器:弓-->
    <!-- ====================================================================-->
    
    <skinWeapon id="weaponBow000" extends="weaponHumanBowBase" cost="0"
                icon="Models/weapon/bow/bow000.mesh.png" file="Models/weapon/bow/bow000.mesh.j3o" 
                applyAttributes="attributeAttack|30" />
    
    <skinWeapon id="weaponBow001" extends="weaponHumanBowBase" cost="1600"
                icon="Models/weapon/bow/bow001.mesh.png" file="Models/weapon/bow/bow001.mesh.j3o"
                applyAttributes="attributeAttack|40" />
    
    <!-- ====================================================================-->
    <!--实质武器:魔杖-->
    <!-- ====================================================================-->
    
    <skinWeapon id="weaponWand000" extends="weaponHumanWandBase" cost="1200"
                icon="Models/weapon/wand/wand000.png" file="Models/weapon/wand/wand000.j3o" 
                applyAttributes="attributeAttack|10,attributeMagicAttack|50,attributeMana|100" />
    
    <!-- ====================================================================-->
    <!--实质武器:魔法书-->
    <!-- ====================================================================-->
    <skinWeapon id="weaponBook000" extends="weaponHumanBookBase" icon="Models/weapon/book/book000.mesh.png" 
                file="Models/weapon/book/book000.mesh.j3o" cost="1200"
                applyAttributes="attributeAttack|5,attributeMagicAttack|40,attributeMana|100" />
    
    <!-- ====================================================================-->
    <!--特殊角色的武器-->
    <!-- ====================================================================-->
    
    <!--Sinbad的大刀-->
    <skinWeapon id="weaponSinbad" icon="" file="Models/monster/sinbad/Sword.j3o" 
                parts="rightHandWeapon" weaponType="rightSword" 
                bindBone="weapon.R" mat="metal" sounds="soundDrawSword" 
                applyAttributes="attributeAttack|25" />

</root>
