=== guyue123/ly/ly-luoying-desktop/bin/Scenes/LuoYing/editor/converter/meta.xsd
<?xml version="1.0"?>
<!--
    转换器定义
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://editor.huliqing.name"
           xmlns="http://editor.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="data" />
                <xs:element ref="converter" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="converter">
        <xs:annotation>
            <xs:documentation>定义一个转换器</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换器名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换器, 格式：name.huliqing.editor.converter.XXXConverter</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="feature">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>feature名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>feature值</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="data">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换tag名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="extends" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>继承自另一个转换器</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converter" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>关联一个转换器定义</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="features" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>数据转换器的配置，格式："feature1,feature2,feature3"，如果不设置这个参数则使用关联的转换器的默认的配置</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
                <xs:element ref="field" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="field">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>指定要转换的字段名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converter" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>关联一个转换器定义</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="base" >
    </xs:complexType>

</xs:schema>

=== guyue123/ly/ly-editor/bin/template/LuoYing-RPG/editor/converter/module.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <converter name="ModuleSwayGeometriesConverter" value="name.huliqing.editor.converter.field.ModuleSwayGeometriesConverter" />
    
    <data name="moduleBase" extends="base">
        <field name="moduleOrder" converter="IntegerTextConverter" />
        <field name="bindMessageEnabledAttribute" converter="TextConverter" />
    </data>

    <data name="moduleActor" extends="moduleBase">
        <field name="radius" converter="FloatTextConverter" />
        <field name="height" converter="FloatTextConverter" />
        <field name="bindDeadAttribute" converter="TextConverter" />
        <field name="bindTargetAttribute" converter="TextConverter" />
        <field name="bindMassAttribute" converter="TextConverter" />
        <field name="bindMovableAttribute" converter="TextConverter" />
        <field name="bindRotatableAttribute" converter="TextConverter" />
        <field name="bindRotatableAttribute" converter="TextConverter" />
        <field name="bindNameAttribute" converter="TextConverter" />
    </data>

    <data name="moduleAction" extends="moduleBase">
        <field name="bindDeadAttribute" converter="TextConverter" />
    </data>

    <data name="moduleChannel" extends="moduleBase">
        <field name="extAnimDir" converter="TextConverter" />
    </data>

    <data name="moduleColor" extends="moduleBase">
        <field name="bindColorAttribute" converter="TextConverter" />
    </data>

    <data name="moduleDrop" extends="moduleBase">
        <field name="bindDeadAttribute" converter="TextConverter" />
    </data>
    
    <data name="moduleItem" extends="moduleBase">
    </data>
    
    <data name="moduleLevel" extends="moduleBase">
        <field name="bindLevelAttribute" converter="TextConverter" />
        <field name="bindXpAttribute" converter="TextConverter" />
        <field name="bindXpNextAttribute" converter="TextConverter" />
        <field name="bindLevelUpEnabledAttribute" converter="TextConverter" />
        <field name="xpLevelEl" converter="TextConverter" />
        <field name="maxLevel" converter="IntegerTextConverter" />
        <field name="effect" converter="TextConverter" />
    </data>
    
    <data name="moduleLod" extends="moduleBase">
        <field name="distTolerance" converter="FloatTextConverter" />
        <field name="trisPerPixel" converter="FloatTextConverter" />
    </data>

    <data name="moduleLogic" extends="moduleBase">
        <field name="bindEnabledAttribute" converter="TextConverter" />
    </data>

    <data name="modulePhysics" extends="moduleBase">
        <field name="mass" converter="FloatTextConverter" />
        <field name="friction" converter="FloatTextConverter" />
        <field name="restitution" converter="FloatTextConverter" />
        <field name="kinematic" converter="CheckBoxConverter" />
        <field name="physicsShape" converter="DataComponentConverter">
            <feature name="componentType" value="physicsShape" />
        </field>
        <field name="angularDamping" converter="FloatTextConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="angularFactor" converter="FloatTextConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="angularSleepingThreshold" converter="FloatTextConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="angularVelocity" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="applyPhysicsLocal" converter="CheckBoxConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="ccdMotionThreshold" converter="FloatTextConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="ccdSweptSphereRadius" converter="FloatTextConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="collideWithGroups" converter="IntegerTextConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="collisionGroup" converter="IntegerTextConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="kinematicSpatial" converter="CheckBoxConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="linearDamping" converter="FloatTextConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="linearSleepingThreshold" converter="FloatTextConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="linearFactor" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="linearVelocity" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
    </data>

    <data name="moduleResist" extends="moduleBase">
    </data>

    <data name="moduleSkill" extends="moduleBase">
        <field name="idleSkillTypes" converter="TextConverter" />
        <field name="waitSkillTypes" converter="TextConverter" />
        <field name="walkSkillTypes" converter="TextConverter" />
        <field name="runSkillTypes" converter="TextConverter" />
        <field name="hurtSkillTypes" converter="TextConverter" />
        <field name="deadSkillTypes" converter="TextConverter" />
        <field name="bindDeadAttribute" converter="TextConverter" />
        <field name="bindHurtAttributes" converter="TextConverter" />
    </data>

    <data name="moduleSkin" extends="moduleBase">
        <field name="bindWeaponSlotAttribute" converter="TextConverter" />
    </data>

    <data name="moduleState" extends="moduleBase">
    </data>

    <data name="moduleSway" extends="moduleBase">
        <field name="sway" converter="CheckBoxConverter" />
        <field name="swayFrequency" converter="FloatTextConverter" />
        <field name="swayVariation" converter="FloatTextConverter" />
        <field name="swayDistance" converter="FloatTextConverter" />
        <field name="swayWind" converter="Vector2fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="swayGeometries" converter="ModuleSwayGeometriesConverter" />
    </data>

    <data name="moduleTalent" extends="moduleBase">
        <field name="bindLevelAttribute" converter="TextConverter" />
        <field name="bindTalentPointsAttribute" converter="TextConverter" />
        <field name="talentPointsLevelEl" converter="TextConverter" />
    </data>

    <data name="moduleTask" extends="moduleBase">
    </data>

    
</root>

=== guyue123/ly/ly-editor/bin/template/LuoYing-RPG/editor/converter/skin.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="skinBase" extends="base">
        <field name="icon" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="file" converter="FileConverter">
            <feature name="filters" value="Model Files|*.j3o,All Files|*.*" />
        </field>
        <field name="baseSkin" converter="CheckBoxConverter" />
        <field name="parts" converter="TextConverter" />
        <field name="conflictParts" converter="TextConverter" />
        <field name="bindBone" converter="TextConverter" />
        <field name="localLocation" converter="Vector3fConverter" />
        <field name="localRotation" converter="Vector3fConverter" />
        <field name="localScale" converter="Vector3fConverter" />
        <field name="applyAttributes" converter="TextConverter" />
        <field name="checkEl" converter="TextConverter" />
        <field name="sounds" converter="TextConverter" />
        <field name="mat" converter="TextConverter" />
        <field name="total" converter="IntegerTextConverter" />
        <field name="tradeInfos" converter="TextConverter" />
    </data>

    <data name="skinOutfit" extends="skinBase">
    </data>

    <data name="skinWeapon" extends="skinBase">
        <field name="weaponType" converter="TextConverter" />
        <field name="slots" converter="TextConverter" />
    </data>
    
    
    
</root>

=== guyue123/ly/ly-luoying-desktop/bin/Scenes/LuoYing/editor/converter/shape.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="shapeBase" extends="base">
    </data>

    <data name="shapeBox" extends="shapeBase">
        <field name="extents" converter="Vector3fConverter" />
    </data>

    <data name="shapeCustom" extends="shapeBase">
        <field name="file" converter="FileConverter">
            <feature name="filters" value="Model Files|*.j3o,All Files|*.*" />
        </field>
    </data>

    <data name="shapeSphere" extends="shapeBase">
        <field name="radius" converter="FloatTextConverter" />
        <field name="zSamples" converter="IntegerTextConverter" />
        <field name="radialSamples" converter="IntegerTextConverter" />
    </data>
    
    
    
</root>

=== guyue123/ly/ly-editor/data/template/LuoYing-RPG/editor/converter/resist.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="resistBase" extends="base">
        <field name="icon" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="value" converter="FloatTextConverter" />
    </data>

    <data name="resistSimple" extends="resistBase">
        <field name="states" converter="TextConverter" />
    </data>

    <data name="resistAll" extends="resistBase">
        <field name="excepts" converter="TextConverter" />
    </data>

    <data name="resistGroup" extends="resistBase">
        <field name="resists" converter="TextConverter" />
    </data>
    
</root>

=== guyue123/ly/ly-luoying-desktop/assets/Scenes/LuoYing/editor/converter/magic.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="magicBase" extends="base">
        <field name="useTime" converter="FloatTextConverter" />
        <field name="hitCheckEl" converter="TextConverter" />
        <field name="effects" converter="TextConverter" />
        <field name="sounds" converter="TextConverter" />
    </data>

    <data name="magicState" extends="magicBase">
        <field name="states" converter="TextConverter" />
        <field name="actorAnims" converter="TextConverter" />
    </data>
    
    <data name="magicAttributeHit" extends="magicBase">
        <field name="attributes" converter="TextConverter" />
        <field name="interval" converter="FloatTextConverter" />
        <field name="distance" converter="FloatTextConverter" />
    </data>
    
</root>

=== guyue123/ly/ly-editor/bin/template/LuoYing-RPG/editor/converter/el.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="elBase" extends="base">
    </data>

    <data name="elCustom" extends="elBase">
        <field name="expression" converter="TextConverter" />
    </data>

    <data name="elLNumber" extends="elBase">
        <field name="expression" converter="TextConverter" />
    </data>

    <data name="elSBoolean" extends="elBase">
        <field name="expression" converter="TextConverter" />
    </data>

    <data name="elSTBoolean" extends="elBase">
        <field name="expression" converter="TextConverter" />
    </data>

    <data name="elSTNumber" extends="elBase">
        <field name="expression" converter="TextConverter" />
    </data>

    <data name="elSkillHitNumber" extends="elBase">
        <field name="expression" converter="TextConverter" />
    </data>
    
    
    
</root>

=== guyue123/ly/ly-editor/data/template/LuoYing-RPG/editor/converter/physicsShape.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="physicsShapeBase" extends="base">
    </data>
    
    <data name="physicsShapeBox" extends="physicsShapeBase">
        <field name="extents" converter="Vector3fConverter" />
    </data>
    
    <data name="physicsShapeCapsule" extends="physicsShapeBase">
        <field name="radius" converter="FloatTextConverter" />
        <field name="height" converter="FloatTextConverter" />
        <field name="axis" converter="ChoiceConverter" >
            <feature name="items" value="0,1,2" />
        </field>
    </data>
    
    <data name="physicsShapeDynamicMesh" extends="physicsShapeBase"/>
    
    <data name="physicsShapeSphere" extends="physicsShapeBase">
        <field name="radius" converter="FloatTextConverter" />
    </data>
    
    <data name="physicsShapeStaticCustomMesh" extends="physicsShapeBase">
        <field name="shape" converter="DataComponentConverter">
            <feature name="componentType" value="shape" />
        </field>
    </data>
    
    <data name="physicsShapeStaticMesh" extends="physicsShapeBase"/>
    
    
</root>

=== guyue123/ly/ly-luoying-desktop/bin/Scenes/LuoYing/editor/converter/actor.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>

    <converter name="EntityObjectDatasConverter" value="name.huliqing.editor.converter.field.EntityObjectDatasConverter" />
    <converter name="ActorSkillsConverter" value="name.huliqing.editor.converter.field.ActorSkillsConverter" />
    
    <data name="actor" extends="entityModelBase">
        <field name="file" converter="FileConverter">
            <feature name="filters" value="Model Files|*.j3o,All Files|*.*" />
        </field>
        <field name="icon" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="channels" converter="EntityObjectDatasConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.ChannelData" />
            <feature name="componentType" value="channel" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="skills" converter="ActorSkillsConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.SkillData" />
            <feature name="componentType" value="skill" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="logics" converter="EntityObjectDatasConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.LogicData" />
            <feature name="componentType" value="logic" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="skins" converter="EntityObjectDatasConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.SkinData" />
            <feature name="componentType" value="skin" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="items" converter="EntityObjectDatasConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.ItemData" />
            <feature name="componentType" value="item" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="talents" converter="EntityObjectDatasConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.TalentData" />
            <feature name="componentType" value="talent" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="resists" converter="EntityObjectDatasConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.ResistData" />
            <feature name="componentType" value="resist" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="drops" converter="EntityObjectDatasConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.DropData" />
            <feature name="componentType" value="drop" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="effects" converter="EntityObjectDatasConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.EffectData" />
            <feature name="componentType" value="effect" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="localForward" converter="TextConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="chat" converter="TextConverter">
            <feature name="collapsed" value="true" />
        </field>
    </data>
    
</root>
