=== guyue123/ly/ly-luoying-desktop/bin/Scenes/LuoYing/editor/converter/meta.xsd
<?xml version="1.0"?>
<!--
    转换器定义
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://editor.huliqing.name"
           xmlns="http://editor.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="data" />
                <xs:element ref="converter" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="converter">
        <xs:annotation>
            <xs:documentation>定义一个转换器</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换器名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换器, 格式：name.huliqing.editor.converter.XXXConverter</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="feature">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>feature名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>feature值</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="data">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换tag名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="extends" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>继承自另一个转换器</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converter" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>关联一个转换器定义</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="features" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>数据转换器的配置，格式："feature1,feature2,feature3"，如果不设置这个参数则使用关联的转换器的默认的配置</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
                <xs:element ref="field" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="field">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>指定要转换的字段名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converter" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>关联一个转换器定义</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="base" >
    </xs:complexType>

</xs:schema>

=== guyue123/ly/ly-luoying-desktop/assets/LuoYing/editor/converter/base.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <!--DataConverters-->
    <converter name="SimpleDataConverter" value="name.huliqing.editor.converter.data.SimpleDataConverter" />
    
    <!--FieldConverters-->
    <converter name="UniqueIdConverter" value="name.huliqing.editor.converter.field.UniqueIdConverter" />
    <converter name="TextConverter" value="name.huliqing.editor.converter.field.TextConverter" />
    <converter name="FloatTextConverter" value="name.huliqing.editor.converter.field.FloatTextConverter" />
    <converter name="IntegerTextConverter" value="name.huliqing.editor.converter.field.IntegerTextConverter" />
    <converter name="LongTextConverter" value="name.huliqing.editor.converter.field.LongTextConverter" />
    <converter name="CheckBoxConverter" value="name.huliqing.editor.converter.field.CheckBoxConverter" />
    <converter name="ChoiceConverter" value="name.huliqing.editor.converter.field.ChoiceConverter" />
    <converter name="ColorConverter" value="name.huliqing.editor.converter.field.ColorConverter" />
    <converter name="Vector2fConverter" value="name.huliqing.editor.converter.field.Vector2fConverter" />
    <converter name="Vector3fConverter" value="name.huliqing.editor.converter.field.Vector3fConverter" />
    <converter name="Vector4fConverter" value="name.huliqing.editor.converter.field.Vector4fConverter" />
    <converter name="QuaternionConverter" value="name.huliqing.editor.converter.field.QuaternionConverter" />
    <converter name="FileConverter" value="name.huliqing.editor.converter.field.FileConverter" />
    <converter name="DataFieldConverter" value="name.huliqing.editor.converter.field.DataFieldConverter" />
    
    <data name="base" extends="" converter="SimpleDataConverter">
        <field name="id" converter="TextConverter">
            <feature name="disabled" value="true" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="uniqueId" converter="UniqueIdConverter" >
            <feature name="disabled" value="true" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="extends" converter="TextConverter">
            <feature name="disabled" value="true" />
            <feature name="collapsed" value="true" />
        </field>
    </data>

    <data name="sound" extends="base" >
        <field name="file" converter="FileConverter" />
        <field name="type" converter="ChoiceConverter" >
            <feature name="items" value="Buffer,Stream" />
        </field>
        <field name="direction" converter="Vector3fConverter" />
        <field name="directional" converter="CheckBoxConverter" />
        <field name="positional" converter="CheckBoxConverter" />
        <field name="innerAngle" converter="TextConverter" />
        <field name="outerAngle" converter="TextConverter" />
        <field name="looping" converter="CheckBoxConverter" />
        <field name="maxDistance" converter="TextConverter" />
        <field name="pitch" converter="TextConverter" />
        <field name="refDistance" converter="TextConverter" />
        <field name="reverbEnabled" converter="CheckBoxConverter" />
        <field name="timeOffset" converter="TextConverter" />
        <field name="velocity" converter="Vector3fConverter" />
        <field name="velocityFromTranslation" converter="CheckBoxConverter" />
        <field name="volume" converter="TextConverter" />
    </data>
    
</root>

=== guyue123/ly/ly-luoying-desktop/assets/Scenes/LuoYing/editor/converter/game.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="gameBase" extends="base">
        <field name="icon" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="scene" converter="DataComponentConverter" >
            <feature name="componentType" value="scene" />
        </field>
        <field name="guiScene" converter="DataComponentConverter">
            <feature name="componentType" value="scene" />
        </field>
        <field name="gameLogics" converter="TextConverter" />
    </data>

    <data name="gameSimple" extends="gameBase" />
    
</root>

=== guyue123/ly/ly-luoying-desktop/assets/Scenes/LuoYing/editor/converter/position.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="positionBase" extends="base">
    </data>

    <data name="positionRandomSphere" extends="positionBase">
        <field name="center" converter="Vector3fConverter" />
        <field name="radius" converter="FloatTextConverter" />
    </data>

    <data name="positionRandomBox" extends="positionBase">
        <field name="min" converter="Vector3fConverter" />
        <field name="max" converter="Vector3fConverter" />
    </data>

    <data name="positionRandomCircle" extends="positionBase">
        <field name="plane" converter="ChoiceConverter" >
            <feature name="items" value="xy,xz,yz" />
        </field>
        <field name="minRadius" converter="FloatTextConverter" />
        <field name="maxRadius" converter="FloatTextConverter" />
        <field name="minOffset" converter="Vector3fConverter" />
        <field name="maxOffset" converter="Vector3fConverter" />
        <field name="order" converter="CheckBoxConverter" />
        <field name="orderInvert" converter="CheckBoxConverter" />
        <field name="orderSize" converter="IntegerTextConverter" />
        <field name="orderStartDegree" converter="FloatTextConverter" />
    </data>

    <data name="positionFixedPoint" extends="positionBase">
        <field name="point" converter="Vector3fConverter" />
    </data>

    <data name="positionView" extends="positionBase">
        <field name="corner" converter="ChoiceConverter" >
            <feature name="items" value="LB,LC,LT,CB,CC,CT,RB,RC,RT" />
        </field>
        <field name="marginWeight" converter="TextConverter" />
    </data>
    
</root>

=== guyue123/ly/ly-editor/bin/template/LuoYing-RPG/editor/converter/slot.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="slotBase" extends="base">
    </data>

    <data name="slot" extends="slotBase">
        <field name="bindBone" converter="TextConverter" />
        <field name="localLocation" converter="Vector3fConverter" />
        <field name="localRotation" converter="Vector3fConverter" />
        <field name="localScale" converter="Vector3fConverter" />
        <field name="hangSkills" converter="TextConverter" />
    </data>
    
</root>

=== guyue123/ly/ly-editor/bin/template/LuoYing-RPG/editor/converter/define.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="defineBase" extends="base">
    </data>

    <data name="defineSkillType" extends="defineBase">
        <field name="skillTypes" converter="TextConverter" />
    </data>

    <data name="defineSkinPart" extends="defineBase">
        <field name="skinParts" converter="TextConverter" />
    </data>

    <data name="defineWeaponType" extends="defineBase">
        <field name="weaponTypes" converter="TextConverter" />
    </data>

    <data name="defineMat" extends="defineBase">
        <field name="mats" converter="TextConverter" />
        <field name="collisionSounds" converter="TextConverter" />
        <field name="collisionEffects" converter="TextConverter" />
    </data>
    
    
    
</root>

=== guyue123/ly/ly-luoying-desktop/assets/LuoYing/editor/converter/module.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    
    <data name="moduleBase" extends="base">
        <field name="moduleOrder" converter="IntegerTextConverter" />
        <field name="bindMessageEnabledAttribute" converter="TextConverter" />
    </data>

    <data name="moduleActor" extends="moduleBase">
        <field name="bindDeadAttribute" converter="TextConverter" />
        <field name="bindTargetAttribute" converter="TextConverter" />
        <field name="bindMassAttribute" converter="TextConverter" />
        <field name="bindMovableAttribute" converter="TextConverter" />
        <field name="bindRotatableAttribute" converter="TextConverter" />
        <field name="bindRotatableAttribute" converter="TextConverter" />
        <field name="bindNameAttribute" converter="TextConverter" />
    </data>

    <data name="moduleAction" extends="moduleBase">
        <field name="bindDeadAttribute" converter="TextConverter" />
    </data>

    <data name="moduleChannel" extends="moduleBase">
        <field name="extAnimDir" converter="TextConverter" />
    </data>

    <data name="moduleColor" extends="moduleBase">
        <field name="bindColorAttribute" converter="TextConverter" />
    </data>

    <data name="moduleDrop" extends="moduleBase">
        <field name="bindDeadAttribute" converter="TextConverter" />
    </data>
    
    <data name="moduleItem" extends="moduleBase">
    </data>
    
    <data name="moduleLevel" extends="moduleBase">
        <field name="bindLevelAttribute" converter="TextConverter" />
        <field name="bindXpAttribute" converter="TextConverter" />
        <field name="bindXpNextAttribute" converter="TextConverter" />
        <field name="bindLevelUpEnabledAttribute" converter="TextConverter" />
        <field name="xpLevelEl" converter="TextConverter" />
        <field name="maxLevel" converter="IntegerTextConverter" />
        <field name="effect" converter="TextConverter" />
    </data>

    <data name="moduleLogic" extends="moduleBase">
        <field name="bindEnabledAttribute" converter="TextConverter" />
    </data>

    <data name="modulePhysics" extends="moduleBase">
        <field name="mass" converter="FloatTextConverter" />
        <field name="friction" converter="FloatTextConverter" />
        <field name="restitution" converter="FloatTextConverter" />
        <field name="kinematic" converter="CheckBoxConverter" />
    </data>

    <data name="moduleResist" extends="moduleBase">
    </data>

    <data name="moduleSkill" extends="moduleBase">
        <field name="idleSkillTypes" converter="TextConverter" />
        <field name="waitSkillTypes" converter="TextConverter" />
        <field name="walkSkillTypes" converter="TextConverter" />
        <field name="runSkillTypes" converter="TextConverter" />
        <field name="hurtSkillTypes" converter="TextConverter" />
        <field name="deadSkillTypes" converter="TextConverter" />
        <field name="bindDeadAttribute" converter="TextConverter" />
        <field name="bindHurtAttributes" converter="TextConverter" />
    </data>

    <data name="moduleSkin" extends="moduleBase">
        <field name="bindWeaponSlotAttribute" converter="TextConverter" />
    </data>

    <data name="moduleState" extends="moduleBase">
    </data>

    <data name="moduleTalent" extends="moduleBase">
        <field name="bindLevelAttribute" converter="TextConverter" />
        <field name="bindTalentPointsAttribute" converter="TextConverter" />
        <field name="talentPointsLevelEl" converter="TextConverter" />
    </data>

    <data name="moduleTask" extends="moduleBase">
    </data>

    
</root>

=== guyue123/ly/ly-editor/bin/template/LuoYing-RPG/editor/converter/emitter.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="emitterBase" extends="base">
    </data>

    <data name="emitter" extends="emitterBase">
        <field name="numParticles" converter="IntegerTextConverter" />
        <field name="startColor" converter="ColorConverter" />
        <field name="endColor" converter="ColorConverter" />
        <field name="startSize" converter="FloatTextConverter" />
        <field name="endSize" converter="FloatTextConverter" />
        <field name="highLife" converter="FloatTextConverter" />
        <field name="lowLife" converter="FloatTextConverter" />
        <field name="texture" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="imagesX" converter="IntegerTextConverter" />
        <field name="imagesY" converter="IntegerTextConverter" />
        <field name="gravity" converter="Vector3fConverter" />
        <field name="initialVelocity" converter="Vector3fConverter" />
        <field name="velocityVariation" converter="FloatTextConverter" />
        <field name="particlesPerSec" converter="IntegerTextConverter" />
        <field name="randomAngle" converter="CheckBoxConverter" />
        <field name="rotateSpeed" converter="FloatTextConverter" />
        <field name="selectRandomImage" converter="CheckBoxConverter" />
        <field name="faceNormal" converter="Vector3fConverter" />
        <field name="facingVelocity" converter="CheckBoxConverter" />
        <field name="shape" converter="DataComponentConverter">
            <feature name="componentType" value="shape" />
        </field>
    </data>
    
    
    
</root>

=== guyue123/ly/ly-editor/data/template/LuoYing-RPG/editor/converter/logic.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="logicBase" extends="base">
        <field name="interval" converter="FloatTextConverter" />
        <field name="enabledCheckEl" converter="TextConverter"/>
        <field name="enemyCheckEl" converter="TextConverter"/>
        <field name="bindTargetAttribute" converter="TextConverter"/>
        <field name="bindViewAttribute" converter="TextConverter"/>
    </data>

    <data name="logicFight" extends="logicBase">
        <field name="fightAction" converter="TextConverter"/>
        <field name="bindAiAttribute" converter="TextConverter"/>
    </data>

    <data name="logicFollow" extends="logicBase">
        <field name="bindFollowAttribute" converter="TextConverter"/>
        <field name="followAction" converter="TextConverter"/>
        <field name="minFollow" converter="FloatTextConverter" />
        <field name="maxFollow" converter="FloatTextConverter" />
    </data>

    <data name="logicNotify" extends="logicBase">
        <field name="distance" converter="FloatTextConverter" />
    </data>

    <data name="logicPosition" extends="logicBase">
        <field name="runAction" converter="TextConverter"/>
        <field name="position" converter="Vector3fConverter" />
        <field name="nearest" converter="FloatTextConverter" />
    </data>

    <data name="logicSearchEnemy" extends="logicBase">
    </data>

    <data name="logicDefend" extends="logicBase">
        <field name="defendRateAttribute" converter="TextConverter" />
        <field name="duckRateAttribute" converter="TextConverter" />
        <field name="listenAttributes" converter="TextConverter" />
        <field name="listenSkillTypes" converter="TextConverter" />
        <field name="defendSkillTypes" converter="TextConverter" />
        <field name="duckSkillTypes" converter="TextConverter" />
    </data>

    <data name="logicIdle" extends="logicBase">
        <field name="idleSimpleAction" converter="TextConverter"/>
        <field name="idlePatrolAction" converter="TextConverter"/>
        <field name="patrolCheckEl" converter="TextConverter"/>
    </data>
    
    <data name="logicShop" extends="logicBase">
        <field name="items" converter="TextConverter" />
        <field name="stockSpeed" converter="FloatTextConverter" />
        <field name="initStock" converter="CheckBoxConverter" />
    </data>
    
    <data name="logicAttributeChange" extends="logicBase">
        <field name="value" converter="FloatTextConverter" />
        <field name="applyAttribute" converter="TextConverter" />
        <field name="bindFactorAttribute" converter="TextConverter"/>
    </data>
    
    
    
</root>
