=== guyue123/ly/ly-luoying-desktop/bin/Scenes/LuoYing/editor/converter/meta.xsd
<?xml version="1.0"?>
<!--
    转换器定义
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://editor.huliqing.name"
           xmlns="http://editor.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="data" />
                <xs:element ref="converter" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="converter">
        <xs:annotation>
            <xs:documentation>定义一个转换器</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换器名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换器, 格式：name.huliqing.editor.converter.XXXConverter</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="feature">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>feature名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>feature值</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="data">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换tag名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="extends" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>继承自另一个转换器</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converter" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>关联一个转换器定义</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="features" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>数据转换器的配置，格式："feature1,feature2,feature3"，如果不设置这个参数则使用关联的转换器的默认的配置</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
                <xs:element ref="field" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="field">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>指定要转换的字段名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converter" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>关联一个转换器定义</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="base" >
    </xs:complexType>

</xs:schema>

=== guyue123/ly/ly-luoying-desktop/assets/Scenes/LuoYing/editor/converter/state.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="stateBase" extends="base">
        <field name="icon" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="useTime" converter="FloatTextConverter" />
        <field name="effects" converter="TextConverter" />
        <field name="animations" converter="TextConverter" />
        <field name="removeOnDead" converter="CheckBoxConverter" />
        <field name="bindDeadAttribute" converter="TextConverter" />
    </data>

    <data name="stateAttributeBase" extends="stateBase">
        <field name="bindNumberAttribute" converter="TextConverter" />
        <field name="addValue" converter="FloatTextConverter" />
        <field name="restore" converter="CheckBoxConverter" />
    </data>

    <data name="stateAttribute" extends="stateAttributeBase" />

    <data name="stateAttributeMove" extends="stateAttributeBase">
        <field name="moveEffect" converter="TextConverter" />
    </data>

    <data name="stateAttributeDynamic" extends="stateBase">
        <field name="bindNumberAttribute" converter="TextConverter" />
        <field name="addValue" converter="FloatTextConverter" />
        <field name="interval" converter="FloatTextConverter" />
    </data>

    <data name="stateBooleanAttribute" extends="stateBase">
        <field name="bindAttribute" converter="TextConverter" />
        <field name="value" converter="CheckBoxConverter" />
        <field name="restore" converter="CheckBoxConverter" />
    </data>

    <data name="stateSkillLocked" extends="stateBase">
        <field name="lockAtSkillTypes" converter="TextConverter" />
        <field name="lockAtFrame" converter="CheckBoxConverter" />
        <field name="lockAllSkillTypes" converter="CheckBoxConverter" />
        <field name="lockSkillTypes" converter="TextConverter" />
        <field name="lockSkillIds" converter="TextConverter" />
        <field name="lockChannels" converter="TextConverter" />
        <field name="lockLocation" converter="CheckBoxConverter" />
    </data>

    <data name="stateClean" extends="stateBase">
        <field name="states" converter="TextConverter" />
    </data>

    <data name="stateGroup" extends="stateBase">
        <field name="states" converter="TextConverter" />
    </data>

    <data name="statePrivateGroup" extends="stateBase">
        <field name="states" converter="TextConverter" />
    </data>
    
    
    
</root>

=== guyue123/ly/ly-editor/bin/template/LuoYing-RPG/editor/converter/attribute.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="attributeBase" extends="base">
        <field name="name" converter="TextConverter" />
    </data>
    
    <data name="attributeBoolean" extends="attributeBase">
        <field name="value" converter="CheckBoxConverter" />
    </data>
    
    <data name="attributeColor" extends="attributeBase">
        <field name="value" converter="ColorConverter" />
    </data>
    
    <data name="attributeFloat" extends="attributeBase">
        <field name="value" converter="FloatTextConverter" />
    </data>
    
    <data name="attributeGroup" extends="attributeBase">
        <field name="attributes" converter="ListDataConverter">
            <feature name="componentType" value="attribute" />
            <feature name="collapsed" value="false" />
        </field>
    </data>
    
    <data name="attributeInteger" extends="attributeBase">
        <field name="value" converter="IntegerTextConverter" />
    </data>
    
    <data name="attributeLevelFloat" extends="attributeBase">
        <field name="value" converter="FloatTextConverter" />
        <field name="level" converter="IntegerTextConverter" />
        <field name="levelEl" converter="TextConverter"/>
    </data>
    
    <data name="attributeLevelInteger" extends="attributeBase">
        <field name="value" converter="IntegerTextConverter" />
        <field name="level" converter="IntegerTextConverter" />
        <field name="levelEl" converter="TextConverter"/>
    </data>
    
    <data name="attributeLimitInteger" extends="attributeBase">
        <field name="value" converter="IntegerTextConverter" />
        <field name="minValue" converter="IntegerTextConverter" />
        <field name="maxValue" converter="IntegerTextConverter" />
        <field name="bindMinLimitAttribute" converter="TextConverter"/>
        <field name="bindMaxLimitAttribute" converter="TextConverter"/>
    </data>
    
    <data name="attributeLong" extends="attributeBase">
        <field name="value" converter="LongTextConverter" />
    </data>
    
    <data name="attributeRelateBoolean" extends="attributeBase">
        <field name="value" converter="CheckBoxConverter" />
        <field name="refVars" converter="TextConverter" />
        <field name="valueEl" converter="TextConverter" />
    </data>
    
    <data name="attributeString" extends="attributeBase">
        <field name="value" converter="TextConverter" />
    </data>
    
    <data name="attributeStringList" extends="attributeBase">
        <field name="value" converter="TextConverter" />
        <field name="duplication" converter="CheckBoxConverter" />
    </data>
    
    <data name="attributeVector2f" extends="attributeBase">
        <field name="value" converter="Vector2fConverter" />
    </data>
    
    <data name="attributeVector3f" extends="attributeBase">
        <field name="value" converter="Vector3fConverter" />
    </data>
    
    <data name="attributeVector4f" extends="attributeBase">
        <field name="value" converter="Vector4fConverter" />
    </data>

    
</root>

=== guyue123/ly/ly-editor/data/template/LuoYing-RPG/editor/converter/item.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="itemBase" extends="base">
        <field name="icon" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="checkEl" converter="TextConverter" />
        <field name="effects" converter="TextConverter" />
        <field name="sounds" converter="TextConverter" />
        <field name="total" converter="IntegerTextConverter" />
        <field name="tradeInfos" converter="TextConverter" />
        <field name="deletable" converter="CheckBoxConverter" />
        <field name="sellable" converter="CheckBoxConverter" />
        <field name="localObject" converter="CheckBoxConverter" />
    </data>

    <data name="itemAttribute" extends="itemBase">
        <field name="attribute" converter="IntegerTextConverter" />
        <field name="amount" converter="FloatTextConverter" />
    </data>

    <data name="itemBook" extends="itemBase">
        <field name="skill" converter="TextConverter" />
    </data>

    <data name="itemMap" extends="itemBase">
        <field name="image" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="locations" converter="TextConverter" />
        <field name="mapSize" converter="FloatTextConverter" />
        <field name="mapAlpha" converter="FloatTextConverter" />
        <field name="locationIcon" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="locationSize" converter="FloatTextConverter" />
        <field name="baseIconPath" converter="TextConverter" />
        <field name="flipVertical" converter="CheckBoxConverter" />
    </data>

    <data name="itemSimple" extends="itemBase">
    </data>

    <data name="itemSkill" extends="itemBase">
        <field name="skill" converter="TextConverter" />
    </data>
    
    <data name="itemState" extends="itemBase">
        <field name="states" converter="TextConverter" />
    </data>
    
    <data name="itemStateRemove" extends="itemBase">
        <field name="states" converter="TextConverter" />
    </data>
    
    <data name="itemSummon" extends="itemBase">
        <field name="actorId" converter="TextConverter" />
        <field name="summonTotal" converter="IntegerTextConverter" />
        <field name="copyAttributesFromSource" converter="TextConverter" />
        <field name="linkAttributesToSource" converter="TextConverter" />
    </data>
    
    
</root>

=== guyue123/ly/ly-editor/data/template/LuoYing-RPG/editor/converter/gameLogic.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="gameLogicBase" extends="base">
        <field name="interval" converter="FloatTextConverter" />
    </data>

    <data name="gameLogicPlayerDeadChecker" extends="gameLogicBase">
    </data>

    <data name="gameLogicActorClean" extends="gameLogicBase">
        <field name="checkEl" converter="TextConverter" />
        <field name="deathDelay" converter="FloatTextConverter" />
    </data>

    <data name="gameLogicAttributeChange" extends="gameLogicBase">
        <field name="checkEl" converter="TextConverter" />
        <field name="applyAttribute" converter="TextConverter" />
        <field name="bindFactorAttribute" converter="TextConverter" />
        <field name="baseValue" converter="FloatTextConverter" />
        <field name="speed" converter="FloatTextConverter" />
    </data>
    
    
</root>

=== guyue123/ly/ly-editor/data/template/LuoYing-RPG/editor/converter/anim.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="animBase" extends="base">
        <field name="debug" converter="CheckBoxConverter" />
        <field name="useTime" converter="FloatTextConverter" />
        <field name="speed" converter="FloatTextConverter" />
        <field name="loop" converter="ChoiceConverter">
            <feature name="items" value="loop,dontLoop,cycle" />
        </field>
        <field name="motionType" converter="ChoiceConverter">
            <feature name="items" value="Linear,Bezier,CatmullRom" />
        </field>
        <field name="bezierFactor" converter="TextConverter" />
        <field name="catmullRomFactor" converter="TextConverter" />
    </data>
    
    <data name="animMove" extends="animBase">
        <field name="startPos" converter="Vector3fConverter" />
        <field name="startPosOffset" converter="Vector3fConverter" />
        <field name="endPos" converter="Vector3fConverter" />
        <field name="endPosOffset" converter="Vector3fConverter" />
        <field name="facing" converter="CheckBoxConverter" />
    </data>
    
    <data name="animCurveMove" extends="animBase">
        <field name="waypoints" converter="TextConverter" />
        <field name="curveTension" converter="FloatTextConverter" />
        <field name="facePath" converter="CheckBoxConverter" />
        <field name="rotationOffset" converter="Vector3fConverter" />
    </data>
    
    <data name="animRotation" extends="animBase">
        <field name="axis" converter="Vector3fConverter" />
        <field name="degree" converter="FloatTextConverter" />
        <field name="invert" converter="CheckBoxConverter" />
        <field name="restore" converter="CheckBoxConverter" />
    </data>
    
    <data name="animInterpolateRotation" extends="animBase">
        <field name="start" converter="Vector3fConverter" />
        <field name="end" converter="Vector3fConverter" />
    </data>
    
    <data name="animRandomRotation" extends="animBase">
        <field name="minDegree" converter="FloatTextConverter" />
        <field name="maxDegree" converter="FloatTextConverter" />
        <field name="axis" converter="Vector3fConverter" />
    </data>
    
    <data name="animScale" extends="animBase">
        <field name="startScale" converter="Vector3fConverter" />
        <field name="endScale" converter="Vector3fConverter" />
        <field name="restore" converter="CheckBoxConverter" />
        <field name="scaleOffset" converter="Vector3fConverter" />
    </data>
    
    <data name="animColor" extends="animBase">
        <field name="startColor" converter="ColorConverter" />
        <field name="endColor" converter="ColorConverter" />
    </data>
    
</root>

=== guyue123/ly/ly-luoying-desktop/assets/LuoYing/editor/converter/entity_filter.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="entityFilterBase" extends="entityBase">
        <feature name="hideFields" value="location,rotation,scale,mat,modules,objectDatas" />
    </data>
    
    <data name="entityBloomFilter" extends="entityFilterBase">
        <field name="bloomIntensity" converter="FloatTextConverter" />
        <field name="blurScale" converter="FloatTextConverter" />
        <field name="downSamplingFactor" converter="FloatTextConverter" />      
        <field name="exposureCutOff" converter="FloatTextConverter" />      
        <field name="exposurePower" converter="FloatTextConverter" /> 
    </data>

    <data name="entityFXAAFilter" extends="entityFilterBase">
        <field name="reduceMul" converter="FloatTextConverter" />      
        <field name="spanMax" converter="FloatTextConverter" />      
        <field name="subPixelShift" converter="FloatTextConverter" />      
        <field name="vxOffset" converter="FloatTextConverter" />      
    </data>

    <data name="entityFogFilter" extends="entityFilterBase">
        <field name="fogColor" converter="ColorConverter" />      
        <field name="fogDensity" converter="FloatTextConverter" />      
        <field name="fogDistance" converter="FloatTextConverter" />      
    </data>

    <data name="entityLightScatteringFilter" extends="entityFilterBase">
        <field name="blurStart" converter="FloatTextConverter" />      
        <field name="blurWidth" converter="FloatTextConverter" />      
        <field name="lightDensity" converter="FloatTextConverter" />      
        <field name="lightPosition" converter="FloatTextConverter" />      
        <field name="nbSamples" converter="IntegerTextConverter" />      
    </data>

    <data name="entitySSAOFilter" extends="entityFilterBase">
        <field name="bias" converter="FloatTextConverter" />      
        <field name="intensity" converter="FloatTextConverter" />      
        <field name="sampleRadius" converter="FloatTextConverter" />      
        <field name="scale" converter="FloatTextConverter" />      
    </data>
    
    

</root>

=== guyue123/ly/ly-luoying-desktop/bin/Scenes/LuoYing/editor/converter/effect.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="effectBase" extends="base" >
        <field name="useTime" converter="FloatTextConverter" />
        <field name="speed" converter="FloatTextConverter" />
        <field name="loop" converter="CheckBoxConverter" />
        <field name="animations" converter="TextConverter" />
        <field name="sounds" converter="TextConverter" />
        <field name="endImmediate" converter="CheckBoxConverter" />
        <field name="location" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="rotation" converter="QuaternionConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="scale" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="shadowMode" converter="ChoiceConverter">
            <feature name="items" value="Off,Cast,Receive,CastAndReceive,Inherit" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="cullHint" converter="ChoiceConverter">
            <feature name="items" value="Inherit,Dynamic,Always,Never" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="queueBucket" converter="ChoiceConverter">
            <feature name="items" value="Opaque,Transparent,Sky,Translucent,Gui,Inherit" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="traceLocation" converter="ChoiceConverter" >
            <feature name="items" value="no,once,always" />
        </field>
        <field name="traceRotation" converter="ChoiceConverter" >
            <feature name="items" value="no,once,always" />
        </field>
        <field name="traceLocationType" converter="ChoiceConverter" >
            <feature name="items" value="origin,origin_bound_center,origin_bound_top,bound_center,bound_top" />
        </field>
        <field name="traceLocationOffset" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="traceRotationOffset" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
    </data>
    
    <data name="effectGroup" extends="effectBase">
        <field name="effects" converter="TextConverter" />
    </data>
    
    <data name="effectParticle" extends="effectBase">
        <field name="emitter" converter="DataComponentConverter" />
        <field name="emitAll" converter="CheckBoxConverter" />
        <field name="randomColor" converter="CheckBoxConverter" />
        <field name="inWorldSpace" converter="CheckBoxConverter" />
        <field name="blendMode" converter="ChoiceConverter" >
            <feature name="items" value="Alpha,AlphaAdditive" />
        </field>
    </data>
    
    <data name="effectTexture" extends="effectBase">
        <field name="texture" converter="TextConverter" />
        <field name="size" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="plane" converter="ChoiceConverter" >
            <feature name="items" value="xy,xz,yz" />
        </field>
        <field name="color" converter="ColorConverter" />
    </data>
    
    <data name="effectModel" extends="effectBase">
        <field name="file" converter="FileConverter">
            <feature name="filters" value="Model Files|*.j3o,All Files|*.*" />
        </field>
    </data>
    
    <data name="effectSlideColorBase" extends="effectBase">
        <field name="startColor" converter="ColorConverter" />
        <field name="endColor" converter="ColorConverter" />
        <field name="mask" converter="FileConverter">
            <feature name="filters" value="Model Files|*.jpg|*.png|*.bmp,All Files|*.*" />
        </field>
        <field name="maskAnimY" converter="CheckBoxConverter" />
        <field name="maskAnimX" converter="CheckBoxConverter" />
        <field name="maskChangeDir" converter="CheckBoxConverter" />
        <field name="maskScaleY" converter="FloatTextConverter" />
        <field name="maskScaleX" converter="FloatTextConverter" />
        <field name="maskSpeed" converter="FloatTextConverter" />
        <field name="maskWrap" converter="ChoiceConverter">
            <feature name="items" value="Repeat,MirroredRepeat" />
        </field>
        <field name="tex" converter="FileConverter">
            <feature name="filters" value="Model Files|*.jpg|*.png|*.bmp,All Files|*.*" />
        </field>
        <field name="texAnimY" converter="CheckBoxConverter" />
        <field name="texAnimX" converter="CheckBoxConverter" />
        <field name="texChangeDir" converter="CheckBoxConverter" />
        <field name="texScaleY" converter="FloatTextConverter" />
        <field name="texScaleX" converter="FloatTextConverter" />
        <field name="texSpeed" converter="FloatTextConverter" />
        <field name="texWrap" converter="ChoiceConverter">
            <feature name="items" value="Repeat,MirroredRepeat" />
        </field>
    </data>
    
    <data name="effectSlideColor" extends="effectSlideColorBase">
    </data>
    
    <data name="effectSlideColorSpline" extends="effectSlideColorBase">
        <field name="fixedPoints" converter="TextConverter" />
        <field name="randomPoints" converter="TextConverter" />
        <field name="width" converter="FloatTextConverter" />
        <field name="segments" converter="IntegerConverter" />
        <field name="tension" converter="FloatTextConverter" />
        <field name="cycle" converter="CheckBoxConverter" />
        <field name="up" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="dimension" converter="IntegerConverter" />
    </data>
    
    <data name="effectSlideColorIOSpline" extends="effectBase">
        <field name="startColor" converter="ColorConverter" />
        <field name="endColor" converter="ColorConverter" />
        <field name="mask" converter="FileConverter">
            <feature name="filters" value="Model Files|*.jpg|*.png|*.bmp,All Files|*.*" />
        </field>
        <field name="tex" converter="FileConverter">
            <feature name="filters" value="Model Files|*.jpg|*.png|*.bmp,All Files|*.*" />
        </field>
        <field name="texChangeDir" converter="CheckBoxConverter" />
        <field name="fixedPoints" converter="TextConverter" />
        <field name="randomPoints" converter="TextConverter" />
        <field name="width" converter="FloatTextConverter" />
        <field name="segments" converter="IntegerConverter" />
        <field name="tension" converter="FloatTextConverter" />
        <field name="cycle" converter="CheckBoxConverter" />
        <field name="up" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="dimension" converter="IntegerConverter" />
        <field name="repeatTimes" converter="IntegerConverter" />
    </data>
    
    <data name="effectProjection" extends="effectBase">
        <field name="texture" converter="FileConverter">
            <feature name="filters" value="Model Files|*.jpg|*.png|*.bmp,All Files|*.*" />
        </field>
        <field name="color" converter="ColorConverter" />
        <field name="projDir" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="projUp" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="projPos" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="debug" converter="CheckBoxConverter" />
    </data>

</root>

=== guyue123/ly/ly-editor/data/template/LuoYing-RPG/editor/converter/drop.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="dropBase" extends="base">
        <field name="sounds" converter="ListDataConverter" />
    </data>

    <data name="dropAttribute" extends="dropBase">
        <field name="attribute" converter="TextConverter" />
        <field name="valueHitEl" converter="TextConverter" />
    </data>

    <data name="dropGroup" extends="dropBase">
        <field name="drops" converter="TextConverter" />
    </data>

    <data name="dropItem" extends="dropBase">
        <field name="item" converter="TextConverter" />
        <field name="count" converter="IntegerTextConverter" />
        <field name="rate" converter="FloatTextConverter" />
    </data>

    <data name="dropSkin" extends="dropBase">
        <field name="skin" converter="TextConverter" />
        <field name="count" converter="IntegerTextConverter" />
        <field name="rate" converter="FloatTextConverter" />
    </data>
    
</root>
