=== guyue123/ly/ly-editor/data/template/LuoYing-RPG/data/meta/talent.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://luoying.huliqing.name"
           xmlns="http://luoying.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="./base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="talentAttribute" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="talentAttribute" >
        <xs:annotation>
            <xs:documentation>属性类型的天赋，这种天</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="talentBase">
                    <xs:attribute name="bindAttribute" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>绑定一个要改变的属性值，角色必须拥有这个属性，否则什么也不会做。</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="valueLevelEl" type="xs:integer" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                指定一个或者直接填写一条LevelEl表达式，这条表达式为当前天赋计算一个等级值，这个值将会添加到所绑定的属性上。
                                示例：#{l}, #{l + 2 * Math:pow(1.06, l)}, 其中"l"(小写的L)表示天赋的当前等级.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="talentBase">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:attribute name="icon" ref="icon" use="required" />
                <xs:attribute name="level" type="xs:integer" use="required">
                    <xs:annotation>
                        <xs:documentation>当前天赋的等级</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="maxLevel" type="xs:integer" use="required">
                    <xs:annotation>
                        <xs:documentation>指定天赋允许的最高等级，当天赋达到这个等级之后将不再升级。</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== guyue123/ly/ly-luoying-desktop/assets/LuoYing/data/talent.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name meta/talent.xsd'>
    
    <!-- ====================================================================-->
    <!--天赋: 
    主要用来配置出不同类型的角色，让角色变得更加鲜明,富有特色和个性。主要由玩家
    自行配置点数来达到效果。
    1.所有天赋都为被动模式，也即不能主动释放。
    2.天赋不会随着等级增长。
    3.天赋可自由增加点数，也即等级，不同等级的天赋影响效果程度不同。
    -->
    <!-- ====================================================================-->

    <!-- ====================================================================-->
    <!--基本属性类天赋-->
    <!-- ====================================================================-->

    <!--生命之源: 提升生命恢复速度，较适合所有-->
    <talentAttribute id="talentLifeRestore" icon="Interface/skill/ysh_07.jpg"  maxLevel="10" 
                     valueLevelEl="elTalentLifeRestore" 
                     bindAttribute="attributeHealthRestore" />

    <!--魔法之源: 提升魔法恢复速度，较适合法系 -->
    <talentAttribute id="talentManaRestore" icon="Interface/skill/ysh_36.jpg"  maxLevel="10" 
                     valueLevelEl="elTalentManaRestore" 
                     bindAttribute="attributeManaRestore" />
    
    <!--御防: 提升防御力，较适合近战系-->
    <talentAttribute id="talentDefence" icon="Interface/skill/ysh_79.jpg"  maxLevel="10" 
                     valueLevelEl="elTalentDefence" 
                     bindAttribute="attributeDefence" />

    <!--御魔: 提升魔法防御力，较适合法系：魔法师、术士、道士等-->
    <talentAttribute id="talentMagicDefence" icon="Interface/skill/ysh_65.jpg"  maxLevel="10" 
                     valueLevelEl="elTalentMagicDefence" 
                     bindAttribute="attributeMagicDefence" />
    
    <!--力量: 提升攻击力,较适合近战系-->
    <talentAttribute id="talentAttack" icon="Interface/skill/ysh_46.jpg"  maxLevel="10" 
                     valueLevelEl="elTalentAttack" 
                     bindAttribute="attributeAttack" />
    
    <!--魔性: 提升魔法攻击力 -->
    <talentAttribute id="talentMagicAttack" icon="Interface/skill/ysh_21.jpg"  maxLevel="10" 
                     valueLevelEl="elTalentMagicAttack" 
                     bindAttribute="attributeMagicAttack" />
 
    <!--鹰眼: 提升角色的视力范围,可提升搜敌范围,普遍适合 -->
    <talentAttribute id="talentVision" icon="Interface/skill/eye.jpg"  maxLevel="10" 
                     valueLevelEl="elTalentVision" 
                     bindAttribute="attributeVision" />
    
    <!--疾风之速: 提升移动速度,较适合远程物理攻击系，如猎人类-->
    <talentAttribute id="talentMoveSpeed" icon="Interface/skill/ysh_71.jpg"  maxLevel="10" 
                     valueLevelEl="elTalentMoveSpeed" 
                     bindAttribute="attributeMoveSpeed" />
    
    <!-- ====================================================================-->
    <!--光环类天赋-->
    <!-- ====================================================================-->
    
    <!-- //TODO -->
    
    <!-- ====================================================================-->
    <!--特殊角色的天赋-->
    <!-- ====================================================================-->

    <!--raptor-->
    <talentAttribute id="talentRaptorMoveSpeed" extends="talentMoveSpeed" level="10" />
    
</root>
