=== guyue123/ly/ly-luoying-desktop/assets/LuoYing/data/meta/bullet.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://luoying.huliqing.name"
           xmlns="http://luoying.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="./base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="bulletBase" />
                <xs:element ref="bulletSimple" />
                <xs:element ref="bulletStraight" />
                <xs:element ref="bulletCurve"  />
                <xs:element ref="bulletCurveTrail" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="bulletCurveTrail">
        <xs:annotation>
            <xs:documentation>曲线路型的子弹,带有拖尾的效果</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="bulletCurveBase">
                    <xs:attribute name="mask" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                拖尾遮罩
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="tex" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                拖尾贴图
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="texScale" type="xs:decimal" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                拖尾贴图Y向缩放
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="color" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                拖尾贴图颜色
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="width" type="xs:decimal" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                拖尾贴图宽度大小
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="dimension" type="xs:integer" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                拖尾的维度，3,4个比较合适，太多影响性能
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="segments" type="xs:integer" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                spline曲面的分段数，默认20，越多越影响性能。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="bulletCurve">
        <xs:annotation>
            <xs:documentation>曲线路型的子弹</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="bulletCurveBase">
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="bulletCurveBase">
        <xs:complexContent>
            <xs:extension base="bulletPathBase">
                <xs:attribute name="tension" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            曲线张力，取值[0.0~1.0],默认0.5
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="positions" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            中间路径点(即不包含开始点和结束点), 关联到position.xml.
                            这些路径点是以子弹的射击方向所在的坐标系为基准进行计算的(初始up=0,1,0)。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="up" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            指定用于计算子弹坐标系的UP方向，格式"x,y,z", 该方向用于计
                            算出子弹的坐标系。默认"0,1,0"
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="bulletStraight">
        <xs:annotation>
            <xs:documentation>直线路型的子弹</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="bulletPathBase"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="bulletSimple">
        <xs:annotation>
            <xs:documentation>直接类型的子弹，没有线路，立即击中目标。</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="bulletBase"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="bulletBase">
        <xs:annotation>
            <xs:documentation>不能直接使用，只作为统一配置用，被用于其它子弹的继承，不要直接在游戏中载入。</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="bulletBase"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="bulletPathBase">
        <xs:annotation>
            <xs:documentation>带有路径的子弹</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="bulletBase">
                <xs:attribute name="baseSpeed" type="xs:decimal" use="optional">
                    <xs:annotation>
                        <xs:documentation>基本速度,一般不需要设置这个值</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="facing" type="bool" use="optional">
                    <xs:annotation>
                        <xs:documentation>子弹是否自动朝向,默认true</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="trace" type="bool" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            是否允许子弹跟踪目标，默认false, 打开后仍需要在运行时设置traceObject才有意义
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
        
    <xs:complexType name="bulletBase">
        <xs:complexContent>
            <xs:extension base="entityModelBase">
                <xs:attribute name="debug" type="bool" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            显示调试信息
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="shape" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>
                            指定一个shape图形，该图形主要是用于碰撞检测及DEBUG所用。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="shapeOffset" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>
                            shape的位置偏移,格式: "x,y,z"
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="timeout" type="xs:decimal" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            超时限制，单位秒，某些子弹可能由于各种原因(速度或FPS问题）
                            导致可能永远无法到达目标位置，如果在这个时间限制之内仍无法到达目标
                            则强制自动退出场景,避免子弹一直停留在场景中．如果子弹确实需要飞行
                            超过这个时间限制，则需要手动加大这个值．
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="effects" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>
                            效果组，这些效果会在子弹开始时跟随着子弹。
                            格式："effect1,effect2,..."
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="hitEffects" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            碰撞效果组，这些效果会在子弹检测到碰撞时发生。
                            格式："effect1,effect2,..."
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="sounds" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            声效组，这些声效会在子弹发射时立即播放。格式：
                            "sound1,sound2,..."
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="hitSounds" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            碰撞声效组，这些声效会在子弹检测到碰撞时播放。格式：
                            "sound1,sound2,..."
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
</xs:schema>

=== guyue123/ly/ly-editor/bin/template/LuoYing-RPG/data/bullet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- play group:0, enemyGroup :1 -->
<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name meta/bullet.xsd'>
    
    <!--=====================================================================-->
    <!--基本配置-->
    <!--=====================================================================-->

    <!--所有子弹的统一配置-->
    <bulletBase id="bulletBase" shape="shapeBulletBox" shapeOffset="0,0,-1.9" baseSpeed="30" timeout="6" 
                debug="0" queueBucket="Translucent" />
    
    <!-- 子弹基本配置-->    
    <bulletStraight id="bulletStraightBase" extends="bulletBase" facing="1" />
    
    <!--快速直线型子弹:不跟随-->
    <bulletStraight id="bulletQuickBase" extends="bulletBase" facing="1" shape="shapeBulletBoxMax" shapeOffset="0,0,-2.9" />
    
    <!--曲线拖尾:不跟随（暂时对跟随效果不友好），但是加大shape -->
    <bulletCurveTrail id="bulletTrailBase" extends="bulletBase" facing="1" shape="shapeBulletBoxMax" shapeOffset="0,0,-2.9"
                      texScale="0.3" width="0.15" tex="Textures/effect/light.jpg" mask="Textures/effect/lightMask.jpg" tension="0.5" />
    
    <!--=====================================================================-->
    <!--通用形子弹-->
    <!--=====================================================================-->
    
    <!-- 默认子弹：直中,无路线 -->
    <bulletSimple id="bulletDefault" extends="bulletBase" />
    
    <!--普通箭-->
    <bulletStraight id="bulletArrow" extends="bulletStraightBase" trace="1" effects="effectBulletArrow" hitSounds="soundBowHit" />

    <!--火弹-->
    <bulletStraight id="bulletTowerFire" extends="bulletStraightBase" trace="1" effects="effectSmokeFire" hitEffects="effectExplosion" />
    
    <!--石弹-->
    <bulletStraight id="bulletTowerStone" extends="bulletStraightBase" trace="0" effects="effectTowerStone" hitEffects="effectExplosion" />
    
    <!--雪弹-->
    <bulletStraight id="bulletSnow" extends="bulletStraightBase" trace="1" effects="effectSnowBullet" hitEffects="effectSnowExplosion" />
    
    <!--增益: 加血，加魔，加状态，会跟随，保证不失手-->
    <bulletCurve id="bulletBuff" extends="bulletStraightBase" shape="shapeBulletBoxMin" shapeOffset="0,0,0" trace="1" effects="effectBuffBullet" hitEffects="effectBuffHit" positions="positionShapeBuff"/>
    
    <!--=====================================================================-->
    <!--特殊技能子弹-->
    <!--=====================================================================-->
    
<!--    闪电箭: 直线型 
    <bulletStraight id="bulletArrowQuick" extends="bulletQuickBase" effects="effectLightningShotBullet" 
                    hitEffects="effectLightningShotHit" hitSounds="soundBowHit" />
    
     落樱飞舞：曲线拖尾 
     <bulletCurveTrail id="bulletCurve" extends="bulletTrailBase"  effects="effectDanceSakuraBullet"
                       hitEffects="effectDanceSakuraHit" positions="positionDanceSakuraWaypoint,positionDanceSakuraWaypoint2" />
    
     电光火石
     <bulletCurve id="bulletFlowLight" extends="bulletStraightBase" trace="1" effects="effectFlowLight" 
                  hitEffects="effectFlowLightHit" positions="positionFlowLight"/>
     
     寒冰箭：拖尾形子弹三连发
     <bulletCurveTrail id="bulletIceTrailUp" extends="bulletTrailBase" effects="effectIceBullet" positions="positionDefShotUp" />
     <bulletCurveTrail id="bulletIceTrailLeft" extends="bulletIceTrailUp" positions="positionDefShotLeft" />
     <bulletCurveTrail id="bulletIceTrailRight" extends="bulletIceTrailUp" positions="positionDefShotRight"  />-->

</root>
