=== guyue123/ly/ly-luoying-desktop/assets/LuoYing/data/meta/resist.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://luoying.huliqing.name"
           xmlns="http://luoying.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="./base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="resistSimple" />
                <xs:element ref="resistAll" />
                <xs:element ref="resistGroup" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="resistSimple">
        <xs:annotation>
            <xs:documentation></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="resistBase">
                    <xs:attribute name="states" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>状态列表, 格式："state1,state2,..."，表示当前抗性可以抵抗的状态列表。</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="resistAll">
        <xs:annotation>
            <xs:documentation>默认可以抵抗所有状态的影响, 但是可以配置一些例外的状态。</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="resistBase">
                    <xs:attribute name="excepts" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>例外状态列表，格式："state1,state2,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="resistGroup">
        <xs:annotation>
            <xs:documentation>抗性组设置，这个组件允许对一系列抗性进行打包，并允许设置初始抗性值。</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="resistBase">
                    <xs:attribute name="resists" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>格式："resist1|value, resist2|value,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="resistBase">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:attribute ref="icon" />
                <xs:attribute name="value" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>抗性值, 该参数取值范围为："0.0~1.0"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
</xs:schema>

=== guyue123/ly/ly-luoying-desktop/src/data/object/resist.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name ../../../../ly-kernel/src/LuoYing/Data/meta/resist.xsd'>

    <!--==========================================================================-->
    <!-- 基本配置 -->
    <!--==========================================================================-->

    <!--火抗:暂无-->
    <resistSimple id="resistFire" value="0" states="" icon="Interface/resist/fire.jpg"/>

    <!--冰抗、霜抗-->
    <resistSimple id="resistIce" value="0" states="stateSnowFrost,stateIceFrozen" icon="Interface/resist/snow.jpg" />
    
    <!--晕抗-->
    <resistSimple id="resistDizzy" value="0" states="stateStun" icon="Interface/resist/dizzy.jpg" />
    
    <!--抗缠绕 -->
    <resistSimple id="resistEntwine" value="0" states="stateSpiderWeb" icon="Interface/resist/entwine.jpg" />
    
    <!--毒抗-->
    <resistSimple id="resistVenom" value="0" states="stateScorpionVenom" icon="Interface/resist/venom.jpg" />
    
    <!--非生命物体的抗性: 除一些特殊及冰霜状态之外，其它都完全免疫 -->
    <resistAll id="resistForNonLife" value="1" excepts="stateSafe,stateSnowFrost,stateIceFrozen" icon="Interface/resist/nonlife.jpg" />
    
    <!--==========================================================================-->
    <!-- 种族、及通用配置打包 -->
    <!--==========================================================================-->
    
    <!--种族配置：人类-->
    <resistGroup id="resistHumanRace" resists="resistFire|0.3,resistIce|0.3,resistDizzy|0.3,resistVenom|0.3" />
    
    <!--种族配置：精灵-->
    <resistGroup id="resistElfRace" resists="resistFire|0.3,resistIce|0.3,resistDizzy|0.1,resistVenom|0.5" />
    
    <!--种族配置：兽人-->
    <resistGroup id="resistOrcRace" resists="resistFire|0.3,resistIce|0.3,resistDizzy|0.5,resistVenom|0.1" />
    
    <!--种族配置：亡灵、不死族--> 
    <resistGroup id="resistUndeadRace" resists="resistFire|0.1,resistIce|0.1,resistDizzy|0.3,resistVenom|1" />
    
    <!--通用：普通野兽-->
    <resistGroup id="resistCreatureGroup" extends="resistOrcRace" />
    
    <!--通用：非生命物体抗性-->
    <resistGroup id="resistNonLifeGroup" resists="resistForNonLife" />
    
    <!--==========================================================================-->
    <!-- 特殊角色抗性 -->
    <!--==========================================================================-->
    
    <!--蝎子的抗性：自己带毒，所以自己100%抗毒-->
    <resistGroup id="resistForScorpion" resists="resistFire|0.2,resistIce|0.2,resistDizzy|0.1,resistVenom|1" />
    
</root>
