=== guyue123/ly/ly-luoying-desktop/assets/LuoYing/editor/component/meta.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://editor.huliqing.name"
           xmlns="http://editor.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="component" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="component">
        <xs:annotation>
            <xs:documentation>定义一个组件</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="id" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>组件id</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="type" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>组件类型</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="icon" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>组件图标，示例："Interface/icon/xxx.png" </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converterClass" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>组件转换器，示例："name.huliqing.editor.components.EntityComponent"</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:complexType name="base" >
    </xs:complexType>

</xs:schema>

=== guyue123/ly/ly-luoying-desktop/bin/Scenes/LuoYing/editor/component/components.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <!--Entity-->
    <component id="entityAmbientLight" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityDirectionalLight" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityPointLight" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entitySpotLight" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />

    <component id="entitySky" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityTerrain" type="entity" icon="" converterClass="name.huliqing.editor.component.TerrainEntityComponentConverter" />
    <component id="entityModel" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entitySimpleWater" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityAdvanceWater" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityBoundary" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityChaseCamera" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityPhysics" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityShadow" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityAudio" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityEffect" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityInstanced" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityBatch" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityNavMesh" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="actor" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    
    <component id="entityBloomFilter" type="entityFilter" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityFXAAFilter" type="entityFilter" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityFogFilter" type="entityFilter" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entityLightScatteringFilter" type="entityFilter" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="entitySSAOFilter" type="entityFilter" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    
    <!--Progress-->
    <component id="progressSimple" type="progress" />
    
    <!--Module-->
    <component id="modulePhysics" type="module" />
    <component id="moduleChannel" type="module" />
    <component id="moduleItem" type="module" />
    <component id="moduleActor" type="module" />
    <component id="moduleSkill" type="module" />
    <component id="moduleSkin" type="module" />
    <component id="moduleAction" type="module" />
    <component id="moduleLogic" type="module" />
    <component id="moduleDrop" type="module" />
    <component id="moduleChat" type="module" />
    <component id="moduleTask" type="module" />
    <component id="moduleState" type="module" />
    <component id="moduleSway" type="module" />
    <component id="moduleResist" type="module" />
    <component id="moduleTalent" type="module" />
    <component id="moduleLevel" type="module" />
    <component id="moduleLod" type="module" />
    <component id="moduleColor" type="module" />
    
    <!--Attribute-->
    <component id="attributeName" type="attribute" />
    <component id="attributeSex" type="attribute" />
    <component id="attributeRace" type="attribute" />
    <component id="attributePlayer" type="attribute" />
    <component id="attributeDead" type="attribute" />
    <component id="attributeBiology" type="attribute" />
    <component id="attributeLevel" type="attribute" />
    <component id="attributeLevelUp" type="attribute" />
    <component id="attributeXp" type="attribute" />
    <component id="attributeXpNext" type="attribute" />
    <component id="attributeGroup" type="attribute" />
    <component id="attributeTeam" type="attribute" />
    <component id="attributeVision" type="attribute" />
    <component id="attributeMoveSpeed" type="attribute" />
    <component id="attributeMass" type="attribute" />
    <component id="attributeMovable" type="attribute" />
    <component id="attributeRotatable" type="attribute" />
    <component id="attributeEssential" type="attribute" />
    <component id="attributeAutoLogic" type="attribute" />
    <component id="attributeAutoAi" type="attribute" />
    <component id="attributeTarget" type="attribute" />
    <component id="attributeFollow" type="attribute" />
    <component id="attributeOwner" type="attribute" />
    <component id="attributeTalentPoints" type="attribute" />
    <component id="attributeHealth" type="attribute" />
    <component id="attributeHealthMax" type="attribute" />
    <component id="attributeMana" type="attribute" />
    <component id="attributeManaMax" type="attribute" />
    <component id="attributeAttack" type="attribute" />
    <component id="attributeMagicAttack" type="attribute" />
    <component id="attributeDefence" type="attribute" />
    <component id="attributeMagicDefence" type="attribute" />
    <component id="attributeHealthRestore" type="attribute" />
    <component id="attributeManaRestore" type="attribute" />
    <component id="attributeAttackSpeed" type="attribute" />
    <component id="attributeMagicSpeed" type="attribute" />
    <component id="attributeDefenceRate" type="attribute" />
    <component id="attributeDuckRate" type="attribute" />
    <component id="attributeGhostRate" type="attribute" />
    <component id="attributeResistInterruptRate" type="attribute" />
    <component id="attributeWeaponSlots" type="attribute" />
    <component id="attributeLocation" type="attribute" />
    <component id="attributeColor" type="attribute" />
    <component id="attributeMessage" type="attribute" />
    <component id="attributeGroupBase" type="attribute" />
    <component id="attributeDynamicBuildingGroup" type="attribute" />
    <component id="attributeStaticBuildingGroup" type="attribute" />
    <component id="attributeCreatureGroup" type="attribute" />
    <component id="attributeHumanFemaleGroup" type="attribute" />
    <component id="attributeHumanMaleGroup" type="attribute" />

    <!--Effect-->
    <component id="effectExplosion" type="effect" />
    <component id="effectSmokeFire" type="effect" />
    <component id="effectSkeletonDead" type="effect" />

    <!--Skill-->
    <component id="skillWait" type="skill" />
    <component id="skillWalk" type="skill" />
    <component id="skillRun" type="skill" />
    <component id="skillJump" type="skill" />
    <component id="skillHurt" type="skill" />
    <component id="skillDead" type="skill" />
    <component id="skillReset" type="skill" />
    <component id="skillIdle" type="skill" />
    <component id="skillSkin" type="skill" />
    <component id="skillDefend" type="skill" />
    <component id="skillDuck" type="skill" />
    <component id="skillMagic" type="skill" />
    <component id="skillMagicBuff" type="skill" />
    <component id="skillFightSimpleAttack" type="skill" />
    <component id="skillFightSimpleAttackShot" type="skill" />
    <component id="skillFightSimpleMagic" type="skill" />
    <component id="skillFightSimpleMagicShot" type="skill" />
    <component id="skillFightTrickAttack" type="skill" />
    <component id="skillFightTrickAttackShot" type="skill" />
    <component id="skillFightTrickMagic" type="skill" />
    <component id="skillFightTrickMagicShot" type="skill" />
    <component id="skillFightSimpleAttackShotBow" type="skill" />
    <component id="skillFightTrickAttackShotBow" type="skill" />
    <component id="skillSummon" type="skill" />
    <component id="skillSummonCreature" type="skill" />
    
    <!--shape-->
    <component id="shapeBox" type="shape" />
    <component id="shapeSphere" type="shape" />
    <component id="shapeCustom" type="shape" />

    <!--physicsShape-->
    <component id="physicsShapeBox" type="physicsShape" />
    <component id="physicsShapeCapsule" type="physicsShape" />
    <component id="physicsShapeDynamicMesh" type="physicsShape" />
    <component id="physicsShapeSphere" type="physicsShape" />
    <component id="physicsShapeStaticCustomMesh" type="physicsShape" />
    <component id="physicsShapeStaticMesh" type="physicsShape" />
    
    <!-- sounds -->
    <component id="sound" type="sound" />
</root>

=== guyue123/ly/ly-luoying-desktop/assets/LuoYing/editor/component/sysComponent.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <component id="sysEntitySky" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityAmbientLight" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityDirectionalLight" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityTerrain" type="entity" icon="" converterClass="name.huliqing.editor.component.TerrainEntityComponentConverter" />
    <component id="sysEntityModel" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityTree" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntitySimpleWater" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityAdvanceWater" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityBoundary" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityChaseCamera" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityPhysics" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityShadow" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityAudio" type="entity" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysModulePhysics" type="module" icon="" converterClass="" />
    
    <component id="sysEntityBloomFilter" type="entityFilter" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityFXAAFilter" type="entityFilter" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityFogFilter" type="entityFilter" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntityLightScatteringFilter" type="entityFilter" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
    <component id="sysEntitySSAOFilter" type="entityFilter" icon="" converterClass="name.huliqing.editor.component.EntityComponentConverter" />
</root>
