=== guyue123/ly/ly-editor/bin/template/LuoYing-RPG/data/meta/actor.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://luoying.huliqing.name"
           xmlns="http://luoying.huliqing.name"
           elementFormDefault="qualified"
        >
    
    <xs:include schemaLocation="./base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="actor" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="actor">
        <xs:annotation>
            <xs:documentation>定义一个角色</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="actorBase">
                    <xs:attribute name="file" ref="file" use="required"/>
                    <xs:attribute name="icon" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>为角色指定一个图标(64x64), 如：Interface/item/face/female.jpg</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
<!--                    <xs:attribute name="attributes" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                定义角色的所有属性值,格式如："attribute1,attribute2,attribute3,..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>-->
                    <xs:attribute name="channels" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                角色的channel定义,关联一些channel，格式："channel1,channel2,...".
                                如果不设置则默认使用一个包含所有骨骼的channel
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="skills" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                技能列表,半角色逗号分隔
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="logics" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>关联逻辑,多个逻辑使用半角逗号分开，如：logic1,logic2,logic3</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="skinBase" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                角色的基本皮肤，基本皮肤是用来在切换装备后“修补皮肤”缺失的问题。比如当
                                穿上一套上下连身的法袍（同时包含lowerBody和upperBody）后，再使用一件只
                                包含upperBody的装备来换上时，由于法袍被替换，这时角色身上将丢失lowerBody
                                的装备，这时就需要从skinBase中查看是否有lowerBody的基本皮肤来补上，否则角
                                色会缺少下半身的装备模型。
                                注意：基本皮肤中不要指定哪些包含两个或两个以上type部位的皮肤。比如：
                                同时包含lowerBody和upperBody的skin,如上下连身的套装之类的皮肤，这类皮肤
                                会造成在换装备后进行修补的时候又替换掉已经穿上的装备。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="skins" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>指定角色拥有的装备，这些装备是存放在角色包裹上的，格式如: "skin1|total,skin2|total,..."
                                其中total可以省略，默认total=1
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="skinOutfit" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>这个参数指定了正在使用中的装备，关联到一件或多件装备,格式如："skinOutfit1,skinOutfit2,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="skinWeapon" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>这个参数指定了正在使用中的武器，关联到一件或多件武器，格式如："skinWeapon1,skinWeapon2,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="items" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>角色包裹物品列表，半角逗号分隔,格式如: 
                                itemId1|total,itemId2|total,itemId3</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="talents" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                角色的天赋，格式: "talent1,talent2,talent3"
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="resists" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                设置抗性，格式："resist1,resist2,..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="drops" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                角色物品的掉落设置，格式： "drop1,drop2,..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="effects" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                效果列表，格式："effect1,effect2,effect3..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="localForward" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>指定角色原始视角方向,默认情况下为(0,0,1),如果模型默认不是该方向,
                                则需要使用该方向指定模型的正视角方向。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="chat" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                关联到一个Chat
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
        
    <xs:complexType name="actorBase">
        <xs:complexContent>
            <xs:extension base="entityModelBase">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    
</xs:schema>

=== guyue123/ly/ly-luoying-desktop/assets/LuoYing/data/actor.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name meta/actor.xsd'>
    
    <!--==========================================================================-->
    <!--角色基本配置-->
    <!--==========================================================================-->
    
    <!--所有角色基本配置-->
    <actor id="actorBase" objectDatas="chatSimple"
        modules="moduleActor,moduleAction,moduleChannel,moduleChat,moduleItem,moduleLogic
,moduleSkill,moduleSkin,moduleState,moduleTalent,moduleTask,moduleLevel,moduleDrop,moduleColor,moduleResist"
    />
    
    <!--未分类生物：生物、种族未知、性别未知、可移动、可转向的角色。如：虫子、怪物、野兽、飞禽、未知生物等活动类角色. -->
    <actor id="actorCreatureBase" extends="actorBase" 
           attributes="attributeCreatureGroup"
           logics="logicSearchEnemy,logicDynamicFight,logicPatrol,logicFollow,logicDefend"
           resists="resistCreatureGroup"
           />
    
    <!-- 静态建筑物角色，如: 炮塔、宝箱、祭坛、房屋等-->
    <actor id="actorStaticBuildingBase" extends="actorBase" 
           attributes="attributeStaticBuildingGroup"
           logics="logicSearchEnemy,logicStaticFight"
           resists="resistNonLifeGroup"
           />

    <!--种族配置： 人类女性-->
    <actor id="actorHumanFemaleBase" extends="actorBase" 
           attributes="attributeHumanFemale"
            logics="logicSearchEnemy,logicDynamicFight,logicPatrol,logicFollow,logicDefend"
            channels="channelRoot,channelHips,channelWaist,channelHead,channelLeftLeg,channelRightLeg
,channelLeftFoot,channelRightFoot,channelLeftArm,channelRightArm,channelLeftHand,channelRightHand"
            resists="resistHumanRace"
            file="Models/actor/ske.mesh.j3o"
            icon="Interface/face/female1.jpg"
            skinBase="skinEar000,skinEye000,skinFace000,skinFoot000,skinHair010,skinHand000,skinLowerBody000,skinUpperBody000"
            skins="skinLowerBody002|1,weaponSword000"
            skinOutfit="skinFoot003,skinHand003,skinLowerBody003,skinUpperBody003"
            skinWeapon="weaponSword000"
            skills="skillWait,skillWalk,skillRun,skillReset,skillDead,skillHurtFront,skillHurtBack
,skillDefend1,skillDefend2
,skillDuckLeft,skillDuckRight,skillDuckBack,skillDuckLeftRoll,skillDuckRightRoll
,skillAttack,skillAttack2,skillAttack3
,skillBowShot
,skillDualSwordAttack"
            scale="0.2,0.2,0.2" mat="derma"
           />
    
    <!--==========================================================================-->
    <!-- 角色配置 -->
    <!--==========================================================================-->
    
    <!-- 丛林蜘蛛 -->
    <actor id="actorSpider" extends="actorCreatureBase" icon="Interface/face/spider.jpg"
           file="Models/monster/spider/spider.j3o" scale="0.5,0.5,0.5"
           drops="dropSpider"
           skills="skillSpiderWait,skillSpiderHurt,skillSpiderDead,skillSpiderReset,skillSpiderWalk,skillSpiderRun,skillSpiderAttack,skillSpiderWeb" mat="derma"
           skinWeapon="weaponMockAnimalClaw"
           collisionRadius="0.6" />
    
    <!--Raptor-->
    <actor id="actorRaptor" extends="actorCreatureBase" file="Models/monster/raptor/raptor.mesh.j3o" 
           items="itemTonicRed|10,itemTonicBlue|10" icon="Interface/face/dinosaur_raptor.jpg"
           talents="talentRaptorMoveSpeed"
           scale="0.75,0.75,0.75"
           skills="skillRaptorWait,skillRaptorWalk,skillRaptorRun,skillRaptorHurt1,skillRaptorHurt2,skillRaptorDead,skillRaptorAttack,skillRaptorIdle" 
           mat="derma" drops="dropRaptor" collisionShape="capsule" 
           collisionRadius="1.4" collisionHeight="4.2" />
           
    <!--Skeleton-->
    <actor id="actorSkeleton" extends="actorCreatureBase" file="Models/monster/skeleton/skeleton.mesh.j3o" 
           items="" icon="Interface/face/skeleton.jpg" 
           talents="" mat="calcium" resists="resistUndeadRace" drops="" 
           skinWeapon="weaponSword000" 
           scale="0.2,0.2,0.2"
           skills="skillSkeletonWait,skillSkeletonAttack,skillSkeletonDead,skillSkeletonRun
,skillWalk,skillRun,skillReset,skillHurtFront,skillHurtBack,skillBowShot,skillDualSwordAttack," />

</root>
